// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path fill-rule="evenodd" clip-rule="evenodd" d="M48 8c22.091 0 40 17.909 40 40S70.091 88 48 88 8 70.091 8 48 25.909 8 48 8Zm0 20a4 4 0 0 0-4 4v12H32a4 4 0 0 0 0 8h12v12a4 4 0 0 0 8 0V52h12a4 4 0 0 0 0-8H52V32a4 4 0 0 0-4-4Z"/>',
  'AddCircleFilledIcon',
);
