// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M48 8c22.09 0 40 17.91 40 40S70.09 88 48 88 8 70.09 8 48 25.91 8 48 8Zm0 20c-2.21 0-4 1.79-4 4v12H32c-2.21 0-4 1.79-4 4s1.79 4 4 4h12v12c0 2.21 1.79 4 4 4s4-1.79 4-4V52h12c2.21 0 4-1.79 4-4s-1.79-4-4-4H52V32c0-2.21-1.79-4-4-4Z" style="fill-rule:evenodd"/>',
  'AddCircleFilledIcon',
);
