// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="m54.42 76.118-2.219 5.088c-1.623 3.725-6.779 3.725-8.403 0l-2.218-5.088C37.623 67.045 30.5 59.822 21.61 55.87l-6.838-3.04c-3.696-1.643-3.696-7.02 0-8.663l6.455-2.869c9.119-4.053 16.37-11.544 20.258-20.925l2.279-5.499c1.588-3.832 6.884-3.832 8.471 0l2.28 5.499c3.887 9.38 11.14 16.872 20.258 20.925l6.454 2.87c3.697 1.643 3.697 7.02 0 8.663l-6.836 3.039c-8.89 3.952-16.015 11.175-19.97 20.248Z"/>',
  'AIStarFilledIcon',
);
