// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M48 8C25.9 8 8 25.9 8 48s17.9 40 40 40 40-17.9 40-40S70.1 8 48 8Zm0 60c-2.2 0-4-1.8-4-4s1.8-4 4-4 4 1.8 4 4-1.8 4-4 4Zm4-16c0 2.2-1.8 4-4 4s-4-1.8-4-4V32c0-2.2 1.8-4 4-4s4 1.8 4 4v20Z" style="fill-rule:evenodd"/>',
  'AlertCircleFilledIcon',
);
