// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path fill-rule="evenodd" clip-rule="evenodd" d="M62.862 70.23a4.004 4.004 0 0 1 .843 1.277 3.93 3.93 0 0 1-.632 4.03 4.017 4.017 0 0 1-.888.789 4.112 4.112 0 0 1-1.868.655 4.146 4.146 0 0 1-3.346-1.21L33.62 51.944C32.54 50.843 32 49.528 32 48s.54-2.843 1.62-3.945L56.97 20.23a4.048 4.048 0 0 1 1.345-.91 4.148 4.148 0 0 1 2.787-.148 4.151 4.151 0 0 1 1.405.736 4.058 4.058 0 0 1 1.01 1.206 4.004 4.004 0 0 1 .405 1.106A3.977 3.977 0 0 1 64 23a3.909 3.909 0 0 1-.295 1.493 3.968 3.968 0 0 1-.843 1.277L41.075 48l21.787 22.23Z"/>',
  'ArrowLeftOutlinedIcon',
);
