// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path fill-rule="evenodd" clip-rule="evenodd" d="M33.138 70.23a4.004 4.004 0 0 0-.843 1.277 3.93 3.93 0 0 0 .632 4.03 4.017 4.017 0 0 0 .888.789 4.112 4.112 0 0 0 1.868.655 4.146 4.146 0 0 0 3.346-1.21l23.35-23.826C63.46 50.843 64 49.528 64 48s-.54-2.843-1.62-3.945L39.03 20.23a4.048 4.048 0 0 0-1.345-.91 4.148 4.148 0 0 0-2.787-.148 4.151 4.151 0 0 0-1.405.736 4.058 4.058 0 0 0-1.01 1.206 4.004 4.004 0 0 0-.405 1.106A3.977 3.977 0 0 0 32 23a3.909 3.909 0 0 0 .295 1.493 3.968 3.968 0 0 0 .843 1.277L54.925 48 33.138 70.23Z"/>',
  'ArrowRightOutlinedIcon',
);
