// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M74.054 18.001c.047 0 .094.002.141.004h.01a4 4 0 0 1 3.773 3.586c.001.006 0 .013.002.02l.007.1c.002.028.006.055.007.083.004.068.006.137.006.206v52a4 4 0 0 1-8 0V31.665L25.838 75.827a4.006 4.006 0 1 1-5.665-5.666L64.335 26H22a4 4 0 0 1 0-8h52l.054.001Z"/>',
  'ArrowTROutlinedIcon',
);
