// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path fill-rule="evenodd" clip-rule="evenodd" d="M25.77 33.138a4.004 4.004 0 0 0-1.277-.843 3.93 3.93 0 0 0-4.03.632 4.017 4.017 0 0 0-.789.888 4.112 4.112 0 0 0-.655 1.868 4.146 4.146 0 0 0 1.21 3.346l23.826 23.35C45.157 63.46 46.472 64 48 64s2.843-.54 3.945-1.62L75.77 39.03a4.048 4.048 0 0 0 .91-1.345 4.148 4.148 0 0 0 .148-2.787 4.151 4.151 0 0 0-.736-1.405 4.058 4.058 0 0 0-1.206-1.01 4.004 4.004 0 0 0-1.106-.405A3.977 3.977 0 0 0 73 32a3.909 3.909 0 0 0-1.493.295 3.968 3.968 0 0 0-1.277.843L48 54.925 25.77 33.138Z"/>',
  'ArrowDownOutlinedIcon',
);
