// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path fill-rule="evenodd" clip-rule="evenodd" d="M25.77 62.862a4.004 4.004 0 0 1-1.277.843 3.93 3.93 0 0 1-4.03-.632 4.017 4.017 0 0 1-.789-.888 4.112 4.112 0 0 1-.655-1.868 4.146 4.146 0 0 1 1.21-3.346l23.826-23.35C45.157 32.54 46.472 32 48 32s2.843.54 3.945 1.62L75.77 56.97a4.048 4.048 0 0 1 .91 1.345 4.148 4.148 0 0 1 .148 2.787 4.151 4.151 0 0 1-.736 1.405 4.058 4.058 0 0 1-1.206 1.01 4.004 4.004 0 0 1-1.106.405A3.977 3.977 0 0 1 73 64a3.909 3.909 0 0 1-1.493-.295 3.968 3.968 0 0 1-1.277-.843L48 41.075 25.77 62.862Z"/>',
  'ArrowUpOutlinedIcon',
);
