// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M40.32 58c2.21 0 4 1.79 4 4s-1.79 4-4 4H27.4c-2.21 0-4-1.79-4-4s1.79-4 4-4h12.92ZM68 14c8.28 0 14.14 5.86 14.14 5.86C88 25.72 88 34 88 34v28c0 8.28-5.86 14.14-5.86 14.14C76.28 82 68 82 68 82H28c-8.28 0-14.14-5.85-14.14-5.86C8 70.28 8 62 8 62V34c0-8.28 5.86-14.14 5.86-14.14C19.72 14 28 14 28 14h40ZM16 62c0 4.97 3.52 8.48 3.52 8.48C23.03 73.99 28 74 28 74h40c4.97 0 8.48-3.52 8.48-3.52C79.99 66.97 80 62 80 62V44.97H16V62Zm12-40s-4.97 0-8.48 3.52c0 0-3.52 3.51-3.52 8.48v2.97h64V34s0-4.97-3.52-8.48c0 0-3.51-3.52-8.48-3.52H28Z"/>',
  'BankCardOutlinedIcon',
);
