// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M80 64H26.383l9.984 9.033A4 4 0 1 1 31 78.966l-17.685-16A4 4 0 0 1 16 56h64a4 4 0 0 1 0 8ZM12 36a4 4 0 0 0 4 4h64a4 4 0 0 0 2.684-6.966l-17.685-16a4 4 0 1 0-5.367 5.932L69.617 32H16a4 4 0 0 0-4 4Z"/>',
  'ChangeOutlinedIcon',
);
