// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M68 12c11.046 0 20 8.954 20 20v32c0 11.046-8.954 20-20 20H28C16.954 84 8 75.046 8 64V32c0-11.046 8.954-20 20-20h40Zm-40 8c-6.627 0-12 5.373-12 12v32c0 6.627 5.373 12 12 12h2V20h-2Zm38 56h2c6.627 0 12-5.373 12-12V32c0-6.627-5.373-12-12-12h-2v56Zm-28 0h20V20H38v56ZM23 41a4 4 0 0 1 4 4v6a4 4 0 0 1-8 0v-6a4 4 0 0 1 4-4Zm50 0a4 4 0 0 1 4 4v6a4 4 0 0 1-8 0v-6a4 4 0 0 1 4-4Z"/>',
  'ExtractOutlinedIcon',
);
