// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M68 12c11.05 0 20 8.95 20 20v32c0 11.05-8.95 20-20 20H28C16.95 84 8 75.05 8 64V32c0-11.05 8.95-20 20-20h40Zm-40 8c-6.63 0-12 5.37-12 12v32c0 6.63 5.37 12 12 12h2V20h-2Zm38 56h2c6.63 0 12-5.37 12-12V32c0-6.63-5.37-12-12-12h-2v56Zm-28 0h20V20H38v56ZM23 41c2.21 0 4 1.79 4 4v6c0 2.21-1.79 4-4 4s-4-1.79-4-4v-6c0-2.21 1.79-4 4-4Zm50 0c2.21 0 4 1.79 4 4v6c0 2.21-1.79 4-4 4s-4-1.79-4-4v-6c0-2.21 1.79-4 4-4Z"/>',
  'ExtractOutlinedIcon',
);
