// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M51.865 44.135h29.267c2.21 0 3.935 1.725 3.866 3.865 0 2.209-1.726 3.934-3.866 3.865H51.865v29.267c0 2.21-1.725 3.935-3.865 3.866-2.209 0-3.934-1.726-3.865-3.866V51.865H14.868c-2.21 0-3.935-1.725-3.866-3.865.069-2.14 1.726-3.934 3.865-3.865h29.268V14.868c0-2.21 1.725-3.935 3.865-3.866 2.209 0 3.934 1.726 3.865 3.865v29.268Z"/>',
  'FollowOutlinedIcon',
);
