// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M66 50a4 4 0 0 1 4 4v6c0 5.523-4.477 10-10 10h-6a4 4 0 0 1 0-8h6a2 2 0 0 0 2-2v-6a4 4 0 0 1 4-4ZM42 26a4 4 0 0 1 0 8h-6a2 2 0 0 0-2 2v6a4 4 0 0 1-8 0v-6c0-5.523 4.477-10 10-10h6Z"/><path fill-rule="evenodd" clip-rule="evenodd" d="M64 10c12.15 0 22 9.85 22 22v32c0 12.15-9.85 22-22 22H32c-12.15 0-22-9.85-22-22V32c0-12.15 9.85-22 22-22h32Zm-32 8c-7.732 0-14 6.268-14 14v32c0 7.732 6.268 14 14 14h32c7.732 0 14-6.268 14-14V32c0-7.732-6.268-14-14-14H32Z"/>',
  'FullScreenOutlinedIcon',
);
