// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M66 50c2.21 0 4 1.79 4 4v6c0 5.52-4.48 10-10 10h-6c-2.21 0-4-1.79-4-4s1.79-4 4-4h6c1.1 0 2-.9 2-2v-6c0-2.21 1.79-4 4-4ZM42 26c2.21 0 4 1.79 4 4s-1.79 4-4 4h-6c-1.1 0-2 .9-2 2v6c0 2.21-1.79 4-4 4s-4-1.79-4-4v-6c0-5.52 4.48-10 10-10h6Z"/><path d="M64 10c12.15 0 22 9.85 22 22v32c0 12.15-9.85 22-22 22H32c-12.15 0-22-9.85-22-22V32c0-12.15 9.85-22 22-22h32Zm-32 8c-7.73 0-14 6.27-14 14v32c0 7.73 6.27 14 14 14h32c7.73 0 14-6.27 14-14V32c0-7.73-6.27-14-14-14H32Z" style="fill-rule:evenodd"/>',
  'FullScreenOutlinedIcon',
);
