// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M48 49c2.21 0 4 1.79 4 4v10c0 2.21-1.79 4-4 4s-4-1.79-4-4V53c0-2.21 1.79-4 4-4Z"/><path d="M41.93 11.04c3.59-2.73 8.56-2.73 12.15 0l23.29 17.71a21.844 21.844 0 0 1 8.64 17.38v19c0 12.08-9.85 21.88-22 21.88h-32c-12.15 0-22-9.79-22-21.88v-19c0-6.81 3.19-13.24 8.64-17.38l23.29-17.71Zm7.28 6.32c-.72-.55-1.71-.55-2.43 0L23.49 35.07c-3.46 2.63-5.5 6.72-5.5 11.06v19c0 7.69 6.27 13.92 14 13.92h32c7.73 0 14-6.23 14-13.92v-19c0-4.34-2.03-8.42-5.5-11.06L49.2 17.36Z" style="fill-rule:evenodd"/>',
  'HomeOutlinedIcon',
);
