// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M41.93 11.04c3.59-2.73 8.56-2.73 12.15 0l23.29 17.71a21.844 21.844 0 0 1 8.64 17.38v19c0 12.08-9.85 21.88-22 21.88h-32c-12.15 0-22-9.79-22-21.88v-19c0-6.81 3.19-13.24 8.64-17.38l23.29-17.71ZM48 49c-2.21 0-4 1.79-4 4v10c0 2.21 1.79 4 4 4s4-1.79 4-4V53c0-2.21-1.79-4-4-4Z" style="fill-rule:evenodd"/>',
  'HomeFilledIcon',
);
