// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path fill-rule="evenodd" clip-rule="evenodd" d="M41.926 11.045a10.046 10.046 0 0 1 12.148 0l23.29 17.708A21.833 21.833 0 0 1 86 46.13v18.995C86 77.206 76.15 87 64 87H32c-12.15 0-22-9.794-22-21.875V46.13a21.833 21.833 0 0 1 8.636-17.377l23.29-17.708ZM48 49a4 4 0 0 0-4 4v10a4 4 0 1 0 8 0V53a4 4 0 0 0-4-4Z"/>',
  'HomeFilledIcon',
);
