// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M48 49a4 4 0 0 1 4 4v10a4 4 0 1 1-8 0V53a4 4 0 0 1 4-4Z"/><path fill-rule="evenodd" clip-rule="evenodd" d="M41.926 11.044a10.045 10.045 0 0 1 12.148 0l23.29 17.709A21.833 21.833 0 0 1 86 46.129v18.995C86 77.207 76.15 87 64 87H32c-12.15 0-22-9.794-22-21.876V46.13a21.833 21.833 0 0 1 8.636-17.376l23.29-17.709Zm7.289 6.32a2.009 2.009 0 0 0-2.43 0L23.496 35.072A13.893 13.893 0 0 0 18 46.129v18.995c0 7.689 6.268 13.921 14 13.921h32c7.732 0 14-6.233 14-13.92V46.129c0-4.335-2.032-8.423-5.496-11.057l-23.29-17.708Z"/>',
  'HomeOutlinedIcon',
);
