// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M83 53.35C83 72.487 67.33 88 48 88S13 73.3 13 53.35c0-3.724 1.16-8.282 2.663-11.327 1.189-2.408 3.239-1.217 4.015 1.355 1.396 4.629 3.928 6.822 3.928 6.822s-2.094-15.75 14.318-31.5c3.88-3.723 8.28-6.885 12.102-9.313 4.019-2.551 9.395.985 10.83 5.524A26.31 26.31 0 0 0 64.97 22.9C72.924 33.4 83 40.75 83 53.35Z"/>',
  'HotFilledIcon',
);
