// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M48 52a4 4 0 0 1 4 4v12a4 4 0 0 1-8 0V56a4 4 0 0 1 4-4Z"/><path fill-rule="evenodd" clip-rule="evenodd" d="M48 8c11.046 0 20 8.954 20 20v8.4c9.129 1.854 16 9.924 16 19.6v12c0 11.046-8.954 20-20 20H32c-11.046 0-20-8.954-20-20V56c0-9.676 6.871-17.746 16-19.6V28c0-11.046 8.954-20 20-20ZM32 44c-6.627 0-12 5.373-12 12v12c0 6.627 5.373 12 12 12h32c6.627 0 12-5.373 12-12V56c0-6.627-5.373-12-12-12H32Zm16-28c-6.627 0-12 5.373-12 12v8h24v-8c0-6.627-5.373-12-12-12Z"/>',
  'LockOutlinedIcon',
);
