// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M48 52c2.21 0 4 1.79 4 4v12c0 2.21-1.79 4-4 4s-4-1.79-4-4V56c0-2.21 1.79-4 4-4Z"/><path d="M48 8c11.05 0 20 8.95 20 20v8.4c9.13 1.85 16 9.92 16 19.6v12c0 11.05-8.95 20-20 20H32c-11.05 0-20-8.95-20-20V56c0-9.68 6.87-17.75 16-19.6V28c0-11.05 8.95-20 20-20ZM32 44c-6.63 0-12 5.37-12 12v12c0 6.63 5.37 12 12 12h32c6.63 0 12-5.37 12-12V56c0-6.63-5.37-12-12-12H32Zm16-28c-6.63 0-12 5.37-12 12v8h24v-8c0-6.63-5.37-12-12-12Z" style="fill-rule:evenodd"/>',
  'LockOutlinedIcon',
);
