// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M48 8c22.09 0 40 17.91 40 40S70.09 88 48 88 8 70.09 8 48 25.91 8 48 8Zm9.67 20c-1.1 0-2.17.39-2.97 1.09L48 34.91l-6.7-5.82c-.8-.7-1.87-1.09-2.97-1.09-2.39 0-4.33 1.79-4.33 4 0 1.1.49 2.16 1.36 2.91l7.97 6.92h-4.57c-2.39 0-4.33 1.79-4.33 4s1.94 4 4.33 4h4.9v2.18h-4.9c-2.39 0-4.33 1.79-4.33 4s1.94 4 4.33 4h4.9V64c0 2.21 1.94 4 4.33 4s4.33-1.79 4.33-4v-3.99h4.9c2.39 0 4.33-1.79 4.33-4s-1.94-4-4.33-4h-4.9v-2.18h4.9c2.39 0 4.33-1.79 4.33-4s-1.94-4-4.33-4h-4.57l7.97-6.92c.87-.76 1.36-1.81 1.36-2.91 0-2.21-1.94-4-4.33-4Z" style="fill-rule:evenodd"/>',
  'MoneyCircleFilledIcon',
);
