// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M20 40a8 8 0 1 1 0 16 8 8 0 0 1 0-16ZM48 40a8 8 0 1 1 0 16 8 8 0 0 1 0-16ZM76 40a8 8 0 1 1 0 16 8 8 0 0 1 0-16Z"/>',
  'MoreHorizontalOutlinedIcon',
);
