// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M40 76a8 8 0 1 1 16 0 8 8 0 0 1-16 0ZM40 48a8 8 0 1 1 16 0 8 8 0 0 1-16 0ZM40 20a8 8 0 1 1 16 0 8 8 0 0 1-16 0Z"/>',
  'MoreVerticalOutlinedIcon',
);
