// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M48 8c22.09 0 40 17.91 40 40 0 13.09-6.28 24.7-16 32h12c2.21 0 4 1.79 4 4s-1.79 4-4 4H52c-.33 0-.65-.04-.95-.12-1.01.08-2.02.12-3.05.12C25.91 88 8 70.09 8 48S25.91 8 48 8Zm0 50c-3.31 0-6 2.69-6 6s2.69 6 6 6 6-2.69 6-6-2.69-6-6-6ZM32 42c-3.31 0-6 2.69-6 6s2.69 6 6 6 6-2.69 6-6-2.69-6-6-6Zm32 0c-3.31 0-6 2.69-6 6s2.69 6 6 6 6-2.69 6-6-2.69-6-6-6ZM48 26c-3.31 0-6 2.69-6 6s2.69 6 6 6 6-2.69 6-6-2.69-6-6-6Z" style="fill-rule:evenodd"/>',
  'MovieFilledIcon',
);
