// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path fill-rule="evenodd" clip-rule="evenodd" d="M48 8c22.091 0 40 17.909 40 40 0 13.085-6.283 24.702-15.997 32H84a4 4 0 0 1 0 8H52c-.328 0-.646-.04-.951-.115A40.583 40.583 0 0 1 48 88C25.909 88 8 70.091 8 48S25.909 8 48 8Zm0 50a6 6 0 1 0 0 12 6 6 0 0 0 0-12ZM32 42a6 6 0 1 0 0 12 6 6 0 0 0 0-12Zm32 0a6 6 0 1 0 0 12 6 6 0 0 0 0-12ZM48 26a6 6 0 1 0 0 12 6 6 0 0 0 0-12Z"/>',
  'MovieFilledIcon',
);
