// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M82 48c0-18.778-15.222-34-34-34S14 29.222 14 48s15.222 34 34 34v6C25.909 88 8 70.091 8 48S25.909 8 48 8s40 17.909 40 40-17.909 40-40 40v-6c18.778 0 34-15.222 34-34Z" />',
  'NotCheckedCircleOutlinedIcon',
);
