// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<defs><style>.b{fill-rule:evenodd}</style></defs><path class="b" d="M30 12c5.52 0 10 4.48 10 10v52c0 5.52-4.48 10-10 10h-9c-5.52 0-10-4.48-10-10V22c0-5.52 4.48-10 10-10h9Zm-9 8c-1.1 0-2 .9-2 2v52c0 1.1.9 2 2 2h9c1.1 0 2-.9 2-2V22c0-1.1-.9-2-2-2h-9ZM75 12c5.52 0 10 4.48 10 10v52c0 5.52-4.48 10-10 10h-9c-5.52 0-10-4.48-10-10V22c0-5.52 4.48-10 10-10h9Zm-9 8c-1.1 0-2 .9-2 2v52c0 1.1.9 2 2 2h9c1.1 0 2-.9 2-2V22c0-1.1-.9-2-2-2h-9Z"/>',
  'PauseOutlinedIcon',
);
