// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M31.76 12c4.42 0 8 3.58 8 8v56c0 4.42-3.58 8-8 8H19c-4.42 0-8-3.58-8-8V20c0-4.42 3.58-8 8-8h12.76ZM77 12c4.42 0 8 3.58 8 8v56c0 4.42-3.58 8-8 8H64.24c-4.42 0-8-3.58-8-8V20c0-4.42 3.58-8 8-8H77Z"/>',
  'PauseFilledIcon',
);
