// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path fill-rule="evenodd" clip-rule="evenodd" d="M30 12c5.523 0 10 4.477 10 10v52c0 5.523-4.477 10-10 10h-9c-5.523 0-10-4.477-10-10V22c0-5.523 4.477-10 10-10h9Zm-9 8a2 2 0 0 0-2 2v52a2 2 0 0 0 2 2h9a2 2 0 0 0 2-2V22a2 2 0 0 0-2-2h-9ZM75 12c5.523 0 10 4.477 10 10v52c0 5.523-4.477 10-10 10h-9c-5.523 0-10-4.477-10-10V22c0-5.523 4.477-10 10-10h9Zm-9 8a2 2 0 0 0-2 2v52a2 2 0 0 0 2 2h9a2 2 0 0 0 2-2V22a2 2 0 0 0-2-2h-9Z"/>',
  'PauseOutlinedIcon',
);
