// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M31.757 12a8 8 0 0 1 8 8v56a8 8 0 0 1-8 8H19a8 8 0 0 1-8-8V20a8 8 0 0 1 8-8h12.757ZM77 12a8 8 0 0 1 8 8v56a8 8 0 0 1-8 8H64.243a8 8 0 0 1-8-8V20a8 8 0 0 1 8-8H77Z"/>',
  'PauseFilledIcon',
);
