// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M14 22.217c0-9.526 10.655-15.376 18.958-10.407l43.081 25.782c7.948 4.757 7.948 16.058 0 20.815L32.958 84.19C24.655 89.159 14 83.308 14 73.782V22.217Z"/>',
  'PlayFilledIcon',
);
