// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M14 24.93C14 13.24 26.86 6.16 36.8 12.2l38.01 23.07c9.58 5.81 9.58 19.65 0 25.46L36.8 83.8C26.85 89.84 14 82.76 14 71.07V24.93Zm8 46.14c0 5.35 5.95 8.75 10.65 5.89l38.01-23.07c4.45-2.7 4.45-9.09 0-11.78L32.65 19.04c-4.7-2.85-10.65.54-10.65 5.89v46.14Z"/>',
  'PlayOutlinedIcon',
);
