// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M14 22.22c0-9.53 10.66-15.38 18.96-10.41l43.08 25.78c7.95 4.76 7.95 16.06 0 20.81L32.96 84.18C24.66 89.15 14 83.3 14 73.77V22.22Z"/>',
  'PlayFilledIcon',
);
