// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M14 24.93C14 13.239 26.855 6.163 36.803 12.2l38.012 23.068c9.58 5.814 9.58 19.649 0 25.462L36.803 83.8C26.855 89.838 14 82.763 14 71.07V24.93Zm8 46.14c0 5.353 5.949 8.745 10.652 5.89l38.013-23.068c4.447-2.699 4.447-9.086 0-11.785L32.652 19.04C27.95 16.184 22 19.576 22 24.931v46.138Z"/>',
  'PlayOutlinedIcon',
);
