// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M31 52c6.627 0 12 5.373 12 12v10c0 6.627-5.373 12-12 12H21c-6.627 0-12-5.373-12-12V64c0-6.627 5.373-12 12-12h10Zm30 4a4 4 0 0 1 4 4v20a4 4 0 0 1-8 0V60a4 4 0 0 1 4-4Zm18 0a4 4 0 0 1 4 4v20a4 4 0 0 1-8 0V60a4 4 0 0 1 4-4Zm-58 4a4 4 0 0 0-4 4v10a4 4 0 0 0 4 4h10a4 4 0 0 0 4-4V64a4 4 0 0 0-4-4H21ZM31 8c6.627 0 12 5.373 12 12v10c0 6.627-5.373 12-12 12H21c-6.627 0-12-5.373-12-12V20c0-6.627 5.373-12 12-12h10Zm44 0c6.627 0 12 5.373 12 12v10c0 6.627-5.373 12-12 12H65c-6.627 0-12-5.373-12-12V20c0-6.627 5.373-12 12-12h10Zm-54 8a4 4 0 0 0-4 4v10a4 4 0 0 0 4 4h10a4 4 0 0 0 4-4V20a4 4 0 0 0-4-4H21Zm44 0a4 4 0 0 0-4 4v10a4 4 0 0 0 4 4h10a4 4 0 0 0 4-4V20a4 4 0 0 0-4-4H65Z"/>',
  'QRCodeOutlinedIcon',
);
