// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path fill-rule="evenodd" clip-rule="evenodd" d="M48 8.001a4 4 0 0 0-4 4v6a4 4 0 1 0 8 0v-6a4 4 0 0 0-4-4Zm22 4.536A4 4 0 0 0 64.535 14l-3 5.197a4 4 0 0 0 6.928 4l3-5.197a4 4 0 0 0-1.465-5.463ZM24.535 18a4 4 0 0 1 6.927-4l3.001 5.196a4 4 0 0 1-6.927 4L24.536 18Zm2.25 18.787C20.93 42.645 18 49.716 18 58v22h-2a4 4 0 1 0 0 8h64a4 4 0 0 0 0-8h-2V58c0-8.284-2.929-15.355-8.787-21.213C63.355 30.929 56.284 28 48 28s-15.355 2.929-21.213 8.787ZM26 80V58c0-6.075 2.148-11.26 6.444-15.556C36.739 38.148 41.924 36 48 36c6.075 0 11.26 2.148 15.556 6.444C67.852 46.739 70 51.924 70 58v22H26Z"/>',
  'ReportOutlinedIcon',
);
