// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M58.08 11c7.58 0 13.3 3.31 17.15 9.94l9.81 16.88c3.95 6.79 3.95 13.58 0 20.38l-9.81 16.88c-3.85 6.62-9.57 9.94-17.15 9.94H37.93c-7.58 0-13.3-3.31-17.15-9.94L10.97 58.2c-3.95-6.79-3.95-13.58 0-20.38l9.81-16.88C24.63 14.32 30.35 11 37.93 11h20.15ZM48 33c-8.28 0-15 6.72-15 15s6.72 15 15 15c8.28 0 15-6.72 15-15s-6.72-15-15-15Z" style="fill-rule:evenodd"/>',
  'SettingFilledIcon',
);
