// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path fill-rule="evenodd" clip-rule="evenodd" d="M58.075 11c7.583 0 13.3 3.312 17.15 9.936l9.813 16.877c3.95 6.791 3.95 13.583 0 20.374l-9.812 16.877C71.374 81.688 65.658 85 58.076 85H37.924c-7.582 0-13.299-3.312-17.15-9.936l-9.813-16.876c-3.949-6.792-3.949-13.584 0-20.376l9.813-16.875C24.626 14.311 30.343 11 37.925 11h20.15ZM48 33c-8.284 0-15 6.716-15 15 0 8.284 6.716 15 15 15 8.284 0 15-6.716 15-15 0-8.284-6.716-15-15-15Z"/>',
  'SettingFilledIcon',
);
