// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M32 80V26.383l-9.033 9.984A4 4 0 1 1 17.034 31l16-17.685A4 4 0 0 1 40 16v64a4 4 0 0 1-8 0ZM60 12a4 4 0 0 0-4 4v64a4 4 0 0 0 6.966 2.684l16-17.685a4 4 0 1 0-5.932-5.367L64 69.617V16a4 4 0 0 0-4-4Z"/>',
  'SortOutlinedIcon',
);
