// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M32 80V26.38l-9.03 9.98A3.999 3.999 0 1 1 17.03 31l16-17.68A3.999 3.999 0 0 1 40 16v64c0 2.21-1.79 4-4 4s-4-1.79-4-4ZM60 12c-2.21 0-4 1.79-4 4v64a3.999 3.999 0 0 0 6.97 2.68l16-17.68a3.999 3.999 0 1 0-5.94-5.36L64 69.62V16c0-2.21-1.79-4-4-4Z"/>',
  'SortOutlinedIcon',
);
