// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="m27.96 44.69 12.32 12.13 27.75-27.47c1.8-1.8 4.81-1.8 6.61 0 1.8 1.8 1.8 4.71 0 6.52L43.58 66.65c-1.8 1.8-4.81 1.8-6.61 0L21.34 51.31c-1.8-1.8-1.8-4.71 0-6.52s4.71-1.9 6.61-.1Z"/>',
  'SuccessOutlinedIcon',
);
