// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M48 8C25.9 8 8 25.9 8 48s17.9 40 40 40 40-17.9 40-40S70.1 8 48 8Zm17 33.6L46.6 60c-1.5 1.5-4.1 1.5-5.6 0L31 50c-1.5-1.5-1.5-4.1 0-5.6l.1-.1c1.5-1.5 4.1-1.5 5.6 0l7.1 7.1L59.3 36c1.6-1.6 4.1-1.6 5.7 0 1.5 1.5 1.5 4.1 0 5.6Z" style="fill-rule:evenodd"/>',
  'SuccessCircleFilledIcon',
);
