// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="m27.964 44.692 12.322 12.13 27.75-27.469c1.803-1.804 4.808-1.804 6.612 0a4.6 4.6 0 0 1 0 6.517L43.592 66.647c-1.803 1.804-4.809 1.804-6.612 0L21.352 51.308a4.6 4.6 0 0 1 0-6.516c1.804-1.805 4.709-1.905 6.612-.1Z"/>',
  'SuccessOutlinedIcon',
);
