// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M49.98 86c6.28 0 10.17-4.87 10.17-4.87 3.88-4.85 2.46-10.85 2.45-10.91l-2.76-11.53h12.15c6.9 0 10.81-5.62 10.81-5.62 3.91-5.62 1.44-11.99 1.44-11.99l-8.08-20.83C72.21 10.06 61.2 10.01 61.09 10.01H23.1c-5.01 0-8.56 3.51-8.56 3.51-3.55 3.51-3.55 8.46-3.55 8.46v25.86c0 4.49 3.22 7.67 3.22 7.67 3.21 3.17 7.74 3.18 7.76 3.18 8.4 0 11.44 7.74 11.44 7.74l4.47 11.39C41.09 86 49.97 86 49.97 86Z"/>',
  'ThumbDownFilledIcon',
);
