// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M48 88c-11.05 0-20.47-3.91-28.28-11.72C11.91 68.47 8 59.04 8 48c0-11.05 3.91-20.47 11.72-28.28C27.53 11.91 36.96 8 48 8c11.05 0 20.47 3.91 28.28 11.72C84.09 27.53 88 36.96 88 48s-3.91 20.47-11.72 28.28C68.47 84.09 59.04 88 48 88Zm0-8c8.84 0 16.38-3.12 22.63-9.37C76.88 64.38 80 56.84 80 48s-3.12-16.38-9.37-22.63C64.38 19.12 56.84 16 48 16s-16.38 3.12-22.63 9.37C19.12 31.62 16 39.16 16 48s3.12 16.38 9.37 22.63C31.62 76.88 39.16 80 48 80Z" style="fill-rule:evenodd"/><path d="M48 26.49v23.47c0 .55.45 1 1 1h18.85" style="fill:none;stroke:#000;stroke-linecap:round;stroke-width:8px"/>',
  'TimeOutlinedIcon',
);
