// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M48 8c22.091 0 40 17.909 40 40S70.091 88 48 88 8 70.091 8 48 25.909 8 48 8Zm0 14.486a4 4 0 0 0-4 4V49.96a5 5 0 0 0 5 5h18.85a4 4 0 0 0 0-8H52V26.486a4 4 0 0 0-4-4Z"/>',
  'TimeFilledIcon',
);
