// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M48 15c14.773 0 27.994 8.702 37.005 22.44 3.993 6.06 3.993 15.06 0 21.12C75.94 72.298 62.773 81 48 81c-14.715 0-27.937-8.702-37.002-22.44-3.997-6.06-3.997-15.06 0-21.12C20.063 23.702 33.232 15 48 15Zm0 15c-9.94 0-18 8.059-18 18s8.06 18 18 18c9.941 0 18-8.059 18-18s-8.059-18-18-18Zm0 8c5.523 0 10 4.477 10 10s-4.477 10-10 10-10-4.477-10-10 4.477-10 10-10Z"/>',
  'ViewFilledIcon',
);
