// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M48 88c22.1 0 40-17.9 40-40S70.1 8 48 8 8 25.9 8 48s17.9 40 40 40zm0-65c2.8 0 5 2.2 5 5v20c0 1-.3 1.8-.7 2.6-.2.7-.6 1.3-1.2 1.9L35.5 68c-2 2-5.1 2-7.1 0s-2-5.1 0-7.1L43 46.4V28c0-2.8 2.2-5 5-5z"/>',
  'AccessTimeCircleFilledBoldIcon',
);
