// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M48 88C25.9 88 8 70.1 8 48S25.9 8 48 8s40 17.9 40 40-17.9 40-40 40zm0-6c18.8 0 34-15.2 34-34S66.8 14 48 14 14 29.2 14 48s15.2 34 34 34zm3-37h12c1.7 0 3 1.3 3 3s-1.3 3-3 3H51v12c0 1.7-1.3 3-3 3s-3-1.3-3-3V51H33c-1.7 0-3-1.3-3-3s1.3-3 3-3h12V33c0-1.7 1.3-3 3-3s3 1.3 3 3v12z"/>',
  'AddCircleOutlinedIcon',
);
