// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M48 8c22.1 0 40 17.9 40 40S70.1 88 48 88 8 70.1 8 48 25.9 8 48 8zm0 22c-1.7 0-3 1.3-3 3v12H33c-1.7 0-3 1.3-3 3s1.3 3 3 3h12v12c0 1.7 1.3 3 3 3s3-1.3 3-3V51h12c1.7 0 3-1.3 3-3s-1.3-3-3-3H51V33c0-1.7-1.3-3-3-3z"/>',
  'AddCircleFilledIcon',
);
