// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M48 88c22.1 0 40-17.9 40-40S70.1 8 48 8 8 25.9 8 48s17.9 40 40 40zm3.3-43.3h13.3c1.8 0 3.3 1.5 3.3 3.3s-1.5 3.3-3.3 3.3H51.3v13.3c0 1.8-1.5 3.3-3.3 3.3s-3.3-1.5-3.3-3.3V51.3H31.3c-1.8 0-3.3-1.5-3.3-3.3s1.5-3.3 3.3-3.3h13.3V31.3c0-1.8 1.5-3.3 3.3-3.3s3.3 1.5 3.3 3.3v13.4z"/>',
  'AddCircleFilledBoldIcon',
);
