// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M48 1.2c25.8 0 46.8 21 46.8 46.8S73.8 94.8 48 94.8 1.2 73.8 1.2 48 22.2 1.2 48 1.2Zm0 8.3C26.7 9.5 9.5 26.7 9.5 48S26.7 86.5 48 86.5 86.5 69.3 86.5 48 69.3 9.5 48 9.5Zm0 17.8c2.3 0 4.1 1.9 4.1 4.1v12.4h12.4c2.3 0 4.1 1.9 4.1 4.1S66.7 52 64.5 52H52.1v12.4c0 2.3-1.9 4.1-4.1 4.1s-4.1-1.9-4.1-4.1V52H31.5c-2.3 0-4.1-1.9-4.1-4.1s1.9-4.1 4.1-4.1h12.4V31.4c0-2.3 1.9-4.1 4.1-4.1Z" style="fill:#11192d"/>',
  'AddCircleOutlinedBoldIcon',
);
