// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M48 10c2.2 0 4 1.8 4 4v30h30c2.2 0 4 1.8 4 4s-1.8 4-4 4H52v30c0 2.2-1.8 4-4 4s-4-1.8-4-4V52H14c-2.2 0-4-1.8-4-4s1.8-4 4-4h30V14c0-2.2 1.8-4 4-4z"/>',
  'AddLargeIcon',
);
