// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M18 59.2V37.9C18 21.4 31.4 8 48 8s30 13.4 30 29.9v21.3l5.7 11.3c1 2-.5 4.3-2.7 4.3H15c-2.2 0-3.7-2.3-2.7-4.3L18 59.2zm58.1 9.7-3.8-7.6c-.2-.4-.3-.9-.3-1.3V38c0-13.2-10.7-24-24-24S24 24.7 24 38v22c0 .5-.1.9-.3 1.3l-3.8 7.6h56.2zM34.6 83.2c-1.3-1.1-1.4-2.9-.4-4.2 1.1-1.3 3-1.4 4.2-.4 2.7 2.2 6 3.5 9.6 3.5 3.6 0 6.9-1.2 9.6-3.5 1.3-1.1 3.2-.9 4.2.4 1.1 1.3.9 3.2-.4 4.2C57.7 86.3 53 88 48 88s-9.7-1.7-13.4-4.8z"/>',
  'AlarmOutlinedIcon',
);
