// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path class="st0" d="M48 8c22.1 0 40 17.9 40 40S70.1 88 48 88 8 70.1 8 48 25.9 8 48 8zm0 50c-2.7 0-4.9 2.1-5 4.8V65c0 2.8 2.2 5 5 5 2.7 0 4.9-2.1 5-4.8V63c0-2.8-2.2-5-5-5zm0-33c-2.7 0-4.9 2.1-5 4.8V50c0 2.8 2.2 5 5 5 2.7 0 4.9-2.1 5-4.8V30c0-2.8-2.2-5-5-5z"/>',
  'AlertCircleFilledBoldIcon',
);
