// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M79 51c3.9 0 7 3.1 7 7v8c0 3.9-3.1 7-7 7H31c-3.9 0-7-3.1-7-7v-8c0-3.9 3.1-7 7-7h48zm0 6H31c-.6 0-1 .4-1 1v8c0 .6.4 1 1 1h48c.6 0 1-.4 1-1v-8c0-.6-.4-1-1-1zM62 23c3.9 0 7 3.1 7 7v8c0 3.9-3.1 7-7 7H31c-3.9 0-7-3.1-7-7v-8c0-3.9 3.1-7 7-7h31zm0 6H31c-.6 0-1 .4-1 1v8c0 .6.4 1 1 1h31c.6 0 1-.4 1-1v-8c0-.6-.4-1-1-1zM13 14c1.7 0 3 1.3 3 3v62c0 1.7-1.3 3-3 3s-3-1.3-3-3V17c0-1.7 1.3-3 3-3z"/>',
  'AlignLeftFilledIcon',
);
