// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M48 7.8c6.5 0 12.8 1.6 18.4 4.5C71.5 10.1 77 9 83 9c2.2 0 3.7 2.3 2.7 4.3-2 4-3.8 7.6-5.3 10.9 4.9 6.8 7.6 15 7.6 23.6 0 22.1-17.9 40-40 40S8 69.9 8 47.8s17.9-40 40-40zM31 34c-2.2 0-4 1.8-4 4v6c0 2.2 1.8 4 4 4s4-1.8 4-4v-6c0-2.2-1.8-4-4-4zm16 0c-2.2 0-4 1.8-4 4v6c0 2.2 1.8 4 4 4s4-1.8 4-4v-6c0-2.2-1.8-4-4-4z"/>',
  'AliWangWangFilledIcon',
);
