// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M83 9c2.2 0 3.7 2.3 2.7 4.3-2 4-3.8 7.6-5.3 10.9 4.9 6.8 7.6 15 7.6 23.6 0 22.1-17.9 40-40 40S8 69.9 8 47.8s17.9-40 40-40c6.5 0 12.8 1.6 18.4 4.5C71.5 10.1 77 9 83 9zm-15.4 9.3c-.9.4-1.9.4-2.8-.1-5.1-2.9-10.8-4.4-16.8-4.4-18.8 0-34 15.2-34 34s15.2 34 34 34 34-15.2 34-34c0-7.9-2.7-15.3-7.5-21.3-.7-.9-.9-2.1-.4-3.2 1.2-2.4 2.4-5.1 3.9-8-3.7.5-7.2 1.5-10.4 3zM31 34c2.2 0 4 1.8 4 4v6c0 2.2-1.8 4-4 4s-4-1.8-4-4v-6c0-2.2 1.8-4 4-4zm16 0c2.2 0 4 1.8 4 4v6c0 2.2-1.8 4-4 4s-4-1.8-4-4v-6c0-2.2 1.8-4 4-4z"/>',
  'AliWangWangOutlinedIcon',
);
