// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M48 34.4 17.2 68c-1.1 1.2-3 1.3-4.2.2-1.2-1.1-1.3-3-.2-4.2l33-36c1.2-1.3 3.2-1.3 4.4 0l33 36c1.1 1.2 1 3.1-.2 4.2s-3.1 1-4.2-.2L48 34.4z"/>',
  'ArrowUpwardLargeIcon',
);
