// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M76.6 48 43 17.2c-1.2-1.1-1.3-3-.2-4.2s3-1.3 4.2-.2l36 33c1.3 1.2 1.3 3.2 0 4.4l-36 33c-1.2 1.1-3.1 1-4.2-.2s-1-3.1.2-4.2L76.6 48z"/>',
  'ArrowForwardLargeIcon',
);
