// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M48 61.6 78.8 28c1.1-1.2 3-1.3 4.2-.2 1.2 1.1 1.3 3 .2 4.2l-33 36a2.97 2.97 0 0 1-4.4 0l-33-36c-1.1-1.2-1-3.1.2-4.2s3.1-1 4.2.2L48 61.6z"/>',
  'ArrowDownwardLargeIcon',
);
