// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="m48 40.9 21.1 22.8c1.5 1.6 4 1.7 5.7.2 1.6-1.5 1.7-4 .2-5.7l-24-26a4.05 4.05 0 0 0-5.9 0l-24 26c-1.5 1.6-1.4 4.2.2 5.7 1.6 1.5 4.2 1.4 5.7-.2l21-22.8z"/>',
  'ArrowUpwardIcon',
);
