// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M82 37H14v35c0 2.8 2.2 5 5 5h58c2.8 0 5-2.2 5-5V37zm-68-6h68v-7c0-2.8-2.2-5-5-5H19c-2.8 0-5 2.2-5 5v7zm57 32c1.7 0 3 1.3 3 3s-1.3 3-3 3H61c-1.7 0-3-1.3-3-3s1.3-3 3-3h10zM19 13h58c6.1 0 11 4.9 11 11v48c0 6.1-4.9 11-11 11H19c-6.1 0-11-4.9-11-11V24c0-6.1 4.9-11 11-11z"/>',
  'BankCardOutlinedIcon',
);
