// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M88 31H8v-7c0-6.1 4.9-11 11-11h58c6.1 0 11 4.9 11 11v7zm0 6v35c0 6.1-4.9 11-11 11H19c-6.1 0-11-4.9-11-11V37h80zM71 63H61c-1.7 0-3 1.3-3 3s1.3 3 3 3h10c1.7 0 3-1.3 3-3s-1.3-3-3-3z"/>',
  'BankCardFilledIcon',
);
