// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M48 8c22.1 0 40 17.9 40 40S70.1 88 48 88 8 70.1 8 48 25.9 8 48 8zm0 3.3c-20.3 0-36.7 16.4-36.7 36.7S27.7 84.7 48 84.7 84.7 68.3 84.7 48 68.3 11.3 48 11.3zm16.7 33.4c1.8 0 3.3 1.5 3.3 3.3s-1.5 3.3-3.3 3.3H31.3c-1.8 0-3.3-1.5-3.3-3.3s1.5-3.3 3.3-3.3h33.4z"/>',
  'BlockCircleOutlinedThinIcon',
);
