// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M48 88c22.1 0 40-17.9 40-40S70.1 8 48 8 8 25.9 8 48s17.9 40 40 40zM33 45h30c1.7 0 3 1.3 3 3s-1.3 3-3 3H33c-1.7 0-3-1.3-3-3s1.3-3 3-3z"/>',
  'BlockCircleFilledIcon',
);
