// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M94.8 48c0-25.8-21-46.8-46.8-46.8S1.2 22.2 1.2 48s21 46.8 46.8 46.8 46.8-21 46.8-46.8ZM9.5 48C9.5 26.7 26.7 9.5 48 9.5S86.5 26.7 86.5 48 69.3 86.5 48 86.5 9.5 69.3 9.5 48Zm21.9 4.1c-2.3 0-4.1-1.9-4.1-4.1s1.9-4.1 4.1-4.1h33.1c2.3 0 4.1 1.9 4.1 4.1s-1.9 4.1-4.1 4.1H31.4Z" style="fill:#231815;fill-rule:evenodd"/>',
  'BlockCircleOutlinedBoldIcon',
);
