// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M37.1 55H21c-2.1 0-3.6-2.1-2.8-4.1l16-42C34.6 7.8 35.8 7 37 7h27c2.1 0 3.6 2.2 2.8 4.1L57.5 34H75c2.6 0 4 3 2.3 5l-43 49c-2.1 2.4-6 .3-5.2-2.7l8-30.3z"/>',
  'BoltFilledIcon',
);
