// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M65 10c1.7 0 3 1.3 3 3v3h7c6.1 0 11 4.9 11 11v48c0 6.1-4.9 11-11 11H21c-6.1 0-11-4.9-11-11V27c0-6.1 4.9-11 11-11h7v-3c0-1.7 1.3-3 3-3s3 1.3 3 3v3h28v-3c0-1.7 1.3-3 3-3zM28 22h-7c-2.8 0-5 2.2-5 5v48c0 2.8 2.2 5 5 5h54c2.8 0 5-2.2 5-5V27c0-2.8-2.2-5-5-5h-7v3c0 1.7-1.3 3-3 3s-3-1.3-3-3v-3H34v3c0 1.7-1.3 3-3 3s-3-1.3-3-3v-3zm19.8 14c11.4 0 21.1 7 25.1 17-4 10-13.7 17-25.1 17s-21.1-7-25.1-17c4-10 13.7-17 25.1-17zm0 6c-7.7 0-14.7 4.2-18.3 10.8l-.2.2.1.2C33 59.6 39.8 63.8 47.3 64h.4c7.7 0 14.7-4.2 18.3-10.8l.1-.2-.1-.2C62.6 46.3 55.8 42.1 48.2 42h-.4zm.2 5c3.3 0 6 2.7 6 6s-2.7 6-6 6-6-2.7-6-6 2.7-6 6-6z"/>',
  'CalendarVisibleOutlinedIcon',
);
