// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M61.9 12c3.1 0 5.8 2 6.7 4.9l2.2 7.1H77c6.1 0 11 4.9 11 11v40c0 6.1-4.9 11-11 11H19c-6.1 0-11-4.9-11-11V35c0-6.1 4.9-11 11-11h6.3l2.2-7.1c.9-2.9 3.6-4.9 6.7-4.9h27.7zM48 38c-8.3 0-15 6.7-15 15s6.7 15 15 15 15-6.7 15-15-6.7-15-15-15zm0 24c5 0 9-4 9-9s-4-9-9-9-9 4-9 9 4 9 9 9z"/>',
  'CameraFilledIcon',
);
