// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="m25.3 24 2.2-7.1c.9-2.9 3.6-4.9 6.7-4.9h27.7c3.1 0 5.8 2 6.7 4.9l2.2 7.1H77c6.1 0 11 4.9 11 11v40c0 6.1-4.9 11-11 11H19c-6.1 0-11-4.9-11-11V35c0-6.1 4.9-11 11-11h6.3zm2.2 6H19c-2.8 0-5 2.2-5 5v40c0 2.8 2.2 5 5 5h58c2.8 0 5-2.2 5-5V35c0-2.8-2.2-5-5-5h-8.5c-1.3 0-2.5-.9-2.9-2.1l-2.8-9.2c-.1-.4-.5-.7-1-.7H34.1c-.4 0-.8.3-1 .7l-2.8 9.2c-.3 1.2-1.5 2.1-2.8 2.1zM48 68c-8.3 0-15-6.7-15-15s6.7-15 15-15 15 6.7 15 15-6.7 15-15 15zm0-6c5 0 9-4 9-9s-4-9-9-9-9 4-9 9 4 9 9 9z"/>',
  'CameraOutlinedIcon',
);
