// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M78 37H18v15h20c1.7 0 3 1.3 3 3 0 3.9 3.1 7 7 7s7-3.1 7-7c0-1.7 1.3-3 3-3h20V37zm0-6V21c0-2.8-2.2-5-5-5H23c-2.8 0-5 2.2-5 5v10h60zm0 27H60.7c-1.4 5.7-6.5 10-12.7 10s-11.3-4.3-12.7-10H18v17c0 2.8 2.2 5 5 5h50c2.8 0 5-2.2 5-5V58zM23 10h50c6.1 0 11 4.9 11 11v54c0 6.1-4.9 11-11 11H23c-6.1 0-11-4.9-11-11V21c0-6.1 4.9-11 11-11z"/>',
  'CardPackageOutlinedIcon',
);
