// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M58.1 46c.2.1.3.3.5.5.8 1.1.6 2.6-.5 3.4L40.8 63.5c-.4.3-.9.5-1.4.5-1.3 0-2.4-1.1-2.4-2.5v-27c0-.5.2-1.1.5-1.5.8-1.1 2.3-1.3 3.3-.5L58.1 46z"/>',
  'CaretRightIcon',
);
