// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M81.2 70.4c1-1.8 1.7-2.9 2-3.6C86.4 61.1 88 54.7 88 48 88 25.9 70.1 8 48 8S8 25.9 8 48s17.9 40 40 40c7.3 0 14.4-2 20.5-5.7.2-.1.9-.5 1.9-1.1l9.8 2.7c2.2.6 4.3-1.4 3.7-3.7l-2.7-9.8zm-6.1.4 1.6 5.9-5.9-1.6c-.8-.2-1.6-.1-2.3.3-1.7 1-2.7 1.6-3 1.8C60.2 80.3 54.2 82 48 82c-18.8 0-34-15.2-34-34s15.2-34 34-34 34 15.2 34 34c0 5.7-1.4 11.2-4 16-.3.6-1.2 2.1-2.6 4.4-.4.8-.5 1.6-.3 2.4z"/>',
  'ChatOutlinedIcon',
);
