// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M48 8C25.9 8 8 25.9 8 48s17.9 40 40 40c7.3 0 14.4-2 20.5-5.7.2-.1.9-.5 1.9-1.1l9.8 2.7c2.2.6 4.3-1.4 3.7-3.7l-2.7-9.8c1-1.8 1.7-2.9 2-3.6C86.4 61.1 88 54.7 88 48 88 25.9 70.1 8 48 8zm9.6 51.5c1.3-1.1 3.2-.9 4.2.4 1.1 1.3.9 3.2-.4 4.2C57.7 67.3 53 69 48 69s-9.7-1.7-13.4-4.8c-1.3-1.1-1.4-3-.4-4.2 1.1-1.3 3-1.4 4.2-.4 2.7 2.2 6 3.5 9.6 3.5 3.6-.1 6.9-1.3 9.6-3.6z"/>',
  'ChatFilledIcon',
);
