// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M81 80c1.7 0 3 1.3 3 3s-1.3 3-3 3H15c-1.7 0-3-1.3-3-3s1.3-3 3-3h66zm-4-70c6.1 0 11 4.9 11 11v50.7c0 2.2-1.8 4-4 4-1.3 0-2.6-.7-3.3-1.8L63 47c-4.1 2-9.1 3-15 3s-10.9-1-15-3L15.3 73.8c-1.2 1.8-3.7 2.4-5.5 1.1C8.7 74.3 8 73 8 71.7V21c0-6.1 4.9-11 11-11h58z"/>',
  'CinemaFilledIcon',
);
