// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="m53.6 48 21.2 21.2c1.6 1.6 1.6 4.1 0 5.6-1.6 1.6-4.1 1.6-5.6 0L48 53.6 26.8 74.8c-1.6 1.6-4.1 1.6-5.6 0-1.6-1.6-1.6-4.1 0-5.6L42.4 48 21.2 26.8c-1.6-1.6-1.6-4.1 0-5.6s4.1-1.6 5.6 0L48 42.4l21.2-21.2c1.6-1.6 4.1-1.6 5.6 0 1.6 1.6 1.6 4.1 0 5.6L53.6 48z"/>',
  'CloseIcon',
);
