// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M37 10h42c3.9 0 7 3.1 7 7v42c0 3.9-3.1 7-7 7H37c-3.9 0-7-3.1-7-7V17c0-3.9 3.1-7 7-7zm0 6c-.6 0-1 .4-1 1v42c0 .6.4 1 1 1h42c.6 0 1-.4 1-1V17c0-.6-.4-1-1-1H37zm23 56c0-1.7 1.3-3 3-3s3 1.3 3 3v7c0 3.9-3.1 7-7 7H17c-3.9 0-7-3.1-7-7V37c0-3.9 3.1-7 7-7h7c1.7 0 3 1.3 3 3s-1.3 3-3 3h-7c-.6 0-1 .4-1 1v42c0 .6.4 1 1 1h42c.6 0 1-.4 1-1v-7z"/>',
  'CopyOutlinedIcon',
);
