// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M19 24h-4c-1.7 0-3-1.3-3-3s1.3-3 3-3h66c1.7 0 3 1.3 3 3s-1.3 3-3 3H25v53c0 2.8 2.2 5 5 5h36c2.8 0 5-2.2 5-5V22.8c0-1.7 1.3-3 3-3s3 1.3 3 3V77c0 6.1-4.9 11-11 11H30c-6.1 0-11-4.9-11-11V24zm21-10c-1.7 0-3-1.3-3-3s1.3-3 3-3h16c1.7 0 3 1.3 3 3s-1.3 3-3 3H40zm-3 27c0-1.7 1.3-3 3-3s3 1.3 3 3v24c0 1.7-1.3 3-3 3s-3-1.3-3-3V41zm16 0c0-1.7 1.3-3 3-3s3 1.3 3 3v24c0 1.7-1.3 3-3 3s-3-1.3-3-3V41z"/>',
  'DeleteOutlinedIcon',
);
