// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="m26 48 22.8 21.1c1.6 1.5 1.7 4 .2 5.7-1.5 1.6-4 1.7-5.7.2l-26-24a4.05 4.05 0 0 1 0-5.9l26-24c1.6-1.5 4.2-1.4 5.7.2 1.5 1.6 1.4 4.2-.2 5.7L26 48z"/><path d="m56 48 22.8 21.1c1.6 1.5 1.7 4 .2 5.7-1.5 1.7-4 1.7-5.7.2l-26-24a4.05 4.05 0 0 1 0-5.9l26-24c1.6-1.5 4.2-1.4 5.7.2 1.5 1.6 1.4 4.2-.2 5.7L56 48z" opacity=".6"/>',
  'DoubleArrowLeftTwoToneIcon',
);
