// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="m27.3 49.2 19.1 26.6c.6.9 1.9 1.1 2.8.5.2-.1.3-.3.5-.5l19.1-26.6c.6-.9.4-2.1-.5-2.8-.3-.2-.7-.4-1.2-.4H54V20c0-1.1-.9-2-2-2h-8c-1.1 0-2 .9-2 2v26H28.9c-1.1 0-2 .9-2 2 0 .4.1.8.4 1.2z"/>',
  'DownIcon',
);
