// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M69 8c2.7 0 4.9 2.1 5 4.8v.4c.1 1.6 1.4 2.8 3 2.8h1c2.8 0 5 2.2 5 5v8c0 2.8-2.2 5-5 5h-1.2l-3.2 43.8c-.4 5.6-5 10-10.7 10.2H33.4c-5.8 0-10.5-4.4-11-10.2L19.2 34H18c-2.7 0-4.9-2.1-5-4.8V21c0-2.8 2.2-5 5-5h1c1.6 0 2.9-1.3 3-2.8v-.4c.1-2.7 2.3-4.8 5-4.8h42zm1.8 26H25.2l3.2 43.4c.2 2.5 2.2 4.5 4.8 4.6h29.3c2.6 0 4.8-2 5-4.6L70.8 34zM77 22c-4.5 0-8.3-3.3-8.9-7.7V14H27.9v.1c-.5 4.4-4.2 7.8-8.7 7.9H19v6h58v-6z"/>',
  'DrinkOutlinedIcon',
);
