// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M48 8c6.7 0 15 5.4 21.5 13.8C76.7 31 81 42.7 81 55c0 19.9-13.9 33-33 33S15 74.9 15 55c0-12.3 4.3-24 11.5-33.2C33 13.4 41.3 8 48 8zm0 6c-4.5 0-11.3 4.4-16.8 11.5C24.9 33.7 21 44.1 21 55c0 16.5 11.2 27 27 27s27-10.5 27-27c0-10.9-3.9-21.3-10.2-29.5C59.3 18.4 52.5 14 48 14zm-7 49c2.8 0 5 2.2 5 5s-2.2 5-5 5-5-2.2-5-5 2.2-5 5-5zm-9-12c2.2 0 4 1.8 4 4s-1.8 4-4 4-4-1.8-4-4 1.8-4 4-4z"/>',
  'EggOutlinedIcon',
);
