// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M66 12c1.7 0 3 1.3 3 3s-1.3 3-3 3h-2v15.1c0 .2 0 .3.1.4l17 34.7c2.7 5.5.4 12-5 14.7-1.5.7-3.2 1.1-4.8 1.1H24.8c-6.1 0-11-4.9-11-11 0-1.7.4-3.3 1.1-4.8l17-34.7c.1-.1.1-.3.1-.4V18h-2c-1.6 0-2.9-1.2-3-2.8V15c0-1.7 1.3-3 3-3h36zm4.9 49H25.1l-4.8 9.8c-.3.7-.5 1.4-.5 2.2 0 2.8 2.2 5 5 5h46.4c.8 0 1.5-.2 2.2-.5 2.5-1.2 3.5-4.2 2.3-6.7L70.9 61zM58 18H38v15.1c0 1.1-.2 2.1-.7 3.1L28.1 55H68l-9.2-18.8c-.5-1-.7-2-.7-3.1V18z"/>',
  'ExperimentOutlinedIcon',
);
