// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M48 8c22.1 0 40 17.9 40 40S70.1 88 48 88 8 70.1 8 48 25.9 8 48 8zm14 20.9-20.3 7.3c-2.5.9-4.5 2.9-5.4 5.4L28.9 62c-.7 2.1.3 4.4 2.4 5.1.9.3 1.8.3 2.7 0l20.3-7.3c2.5-.9 4.5-2.9 5.4-5.4L67.1 34c.7-2.1-.3-4.4-2.4-5.1-.9-.3-1.8-.3-2.7 0zM48 53c2.8 0 5-2.2 5-5s-2.2-5-5-5-5 2.2-5 5 2.2 5 5 5z"/>',
  'ExploreCircleFilledIcon',
);
