// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M48 78c-14.7 0-27.8-9.3-39.2-27.3-1-1.6-1-3.7 0-5.3C20.2 27.3 33.3 18 48 18s27.8 9.3 39.2 27.3c1 1.6 1 3.7 0 5.3C75.8 68.7 62.7 78 48 78zm0-54c-12.1 0-23.4 7.9-33.8 24C24.6 64.1 35.9 72 48 72c12.1 0 23.4-7.9 33.8-24C71.4 31.9 60.1 24 48 24zm0 38c-7.8 0-14.1-6.3-14.1-14S40.2 34 48 34s14.1 6.3 14.1 14S55.8 62 48 62zm0-6c4.5 0 8.1-3.6 8.1-8s-3.6-8-8.1-8-8.1 3.6-8.1 8 3.6 8 8.1 8z"/>',
  'EyeOutlinedIcon',
);
