// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M85.3 35.6c1.8 3.4 2.7 7.1 2.7 11 0 13.6-11.5 24.5-25.6 24.7H33.5l5.8 6.7c1 1.2.9 3-.2 4.1l-.1.2c-1.2 1-3 .9-4.1-.2l-.1-.1-10-11.7c-1.6-1.9-.3-4.8 2.1-5h35.2c11.1 0 20-8.4 20-18.7 0-2.9-.7-5.6-2-8.2-.8-1.5-.2-3.3 1.3-4 1.4-.8 3.2-.3 3.9 1.2zM61 10.8l.1.1 10 11c1.7 1.9.5 4.9-2 5l-.1.1H34c-11.1 0-20 8.6-20 19.2 0 3 .7 5.8 2 8.4.8 1.5.2 3.3-1.3 4-1.5.8-3.3.2-4-1.3C8.9 53.9 8 50.1 8 46.2c0-13.8 11.4-25 25.6-25.2h28.6l-5.5-6c-1.1-1.2-1-3 .1-4.1l.1-.1c1.1-1 2.8-1 4-.1l.1.1z"/>',
  'FlipOutlinedIcon',
);
