// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M76 13c6.1 0 11 4.9 11 11v48c0 6.1-4.9 11-11 11H22c-6.1 0-11-4.9-11-11V24c0-6.1 4.9-11 11-11h54zm0 6H22c-2.8 0-5 2.2-5 5v48c0 2.8 2.2 5 5 5h54c2.8 0 5-2.2 5-5V24c0-2.8-2.2-5-5-5zM58.6 50.3 69 60.8v-2.5c0-1.6 1.2-2.9 2.8-3h.2c1.7 0 3 1.3 3 3v10c0 1.7-1.3 3-3 3H62c-1.7 0-3-1.3-3-3s1.3-3 3-3h3L54.3 54.6c-1.2-1.2-1.2-3.1 0-4.2s3.1-1.2 4.3-.1zM36.4 24.4c1.7 0 3 1.3 3 3s-1.3 3-3 3h-3l10.7 10.7c1.2 1.2 1.2 3.1 0 4.2-1.2 1.2-3.1 1.2-4.2 0L29.4 34.9v2.5c0 1.6-1.2 2.9-2.8 3h-.2c-1.7 0-3-1.3-3-3v-10c0-1.7 1.3-3 3-3h10z"/>',
  'FullScreenOutlinedIcon',
);
