// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M80 49.3v27c0 6.1-4.9 11-11 11H52v-38h28zm-34 38H29c-6.1 0-11-4.9-11-11v-27h28v38zm6.4-72.5c2.6-4.5 8.4-6.1 13-3.5s6.1 8.4 3.5 13l-1.8 3.1H81c3.8 0 6.9 3 7 6.8v4.2c0 3.9-3.1 7-7 7H17c-3.9 0-7-3.1-7-7v-4c0-3.9 3.1-7 7-7h13.3l-1.8-3.1c-2.6-4.5-1.1-10.4 3.5-13s10.4-1.1 13 3.5l3.7 6.4 3.7-6.4zM35 16.5c-1.7 1-2.2 3.1-1.3 4.8l3.5 6.1h7.9l.1-.2-5.4-9.4c-1-1.7-3.1-2.3-4.8-1.3zm27.4 0c-1.7-1-3.8-.4-4.8 1.3l-5.4 9.4.1.2h7.9l3.5-6.1c.9-1.6.4-3.7-1.1-4.7l-.2-.1z"/>',
  'GiftFilledIcon',
);
