// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M32.4 36h32c1.2 0 2-.8 2-2s-.8-2-2-2h-32c-1.2 0-2 .8-2 2s.8 2 2 2zm32 10h-32c-1.2 0-2 .8-2 2s.8 2 2 2h32c1.2 0 2-.8 2-2s-.8-2-2-2zm0 14h-32c-1.2 0-2 .8-2 2s.8 2 2 2h32c1.2 0 2-.8 2-2s-.8-2-2-2z"/>',
  'GripperBarHorizontalIcon',
);
