// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M61.1 20.3c.4-1.6 2-2.6 3.6-2.3 1.6.4 2.6 2 2.3 3.6L64 35h11c1.6 0 2.9 1.2 3 2.8v.2c0 1.7-1.3 3-3 3H62.6l-3.1 14H75c1.6 0 2.9 1.2 3 2.8v.2c0 1.7-1.3 3-3 3H58.2l-3.3 14.7c-.3 1.6-1.8 2.6-3.4 2.3h-.2c-1.6-.4-2.6-2-2.3-3.6L52 61H38.2l-3.3 14.7c-.3 1.6-1.8 2.6-3.4 2.3h-.2c-1.6-.4-2.6-2-2.3-3.6L32 61H21c-1.6 0-2.9-1.2-3-2.8V58c0-1.7 1.3-3 3-3h12.4l3.1-14H21c-1.6 0-2.9-1.2-3-2.8V38c0-1.7 1.3-3 3-3h16.8l3.3-14.7c.3-1.6 1.8-2.6 3.4-2.3h.2c1.6.4 2.6 2 2.3 3.6L44 35h13.9l3.2-14.7zM56.5 41H42.6l-3.1 14h13.9l3.1-14z"/>',
  'HashOutlinedIcon',
);
