// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M48 8c22.1 0 40 17.9 40 40S70.1 88 48 88 8 70.1 8 48 25.9 8 48 8zm0 55c-1.7 0-3 1.3-3 3s1.3 3 3 3 3-1.3 3-3-1.3-3-3-3zm-.2-35c-4.5 0-8.7 2.3-11.1 5.9-.6 1-1.1 2-1.5 3.1-.5 1.6.4 3.3 1.9 3.8 1.6.5 3.3-.4 3.8-1.9.2-.6.5-1.1.8-1.7 1.3-2 3.6-3.2 6.1-3.2 4 0 7.2 3.1 7.2 7s-3.2 7-7.2 7c-1.7 0-3 1.3-3 3v6c0 1.7 1.3 3 3 3s3-1.3 3-3v-3.3C56.6 52.3 61 47.2 61 41c0-7.2-5.9-13-13.2-13z"/>',
  'HelpCircleFilledIcon',
);
