// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M48 8c22.1 0 40 17.9 40 40S70.1 88 48 88 8 70.1 8 48 25.9 8 48 8zm0 6c-18.8 0-34 15.2-34 34s15.2 34 34 34 34-15.2 34-34-15.2-34-34-34zm13 27c0 6.2-4.4 11.3-10.2 12.7V57c0 1.7-1.3 3-3 3s-3-1.3-3-3v-6c0-1.7 1.3-3 3-3 4 0 7.2-3.1 7.2-7s-3.2-7-7.2-7c-2.5 0-4.8 1.2-6.1 3.2-.3.5-.6 1.1-.8 1.7-.5 1.6-2.2 2.4-3.8 1.9-1.6-.5-2.4-2.2-1.9-3.8.4-1.1.9-2.1 1.5-3.1 2.4-3.7 6.6-5.9 11.1-5.9C55.1 28 61 33.8 61 41zM48 69c-1.7 0-3-1.3-3-3s1.3-3 3-3 3 1.3 3 3-1.3 3-3 3z"/>',
  'HelpCircleOutlinedIcon',
);
