// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="m77.1 44.4 4.9 2.7C81.5 28.7 66.5 14 48 14c-18.8 0-34 15.2-34 34s15.2 34 34 34c11.5 0 22-5.7 28.3-15.1.9-1.4 2.8-1.7 4.2-.8 1.4.9 1.7 2.8.8 4.2C73.9 81.2 61.5 88 48 88 25.9 88 8 70.1 8 48S25.9 8 48 8s40 17.9 40 40c0 1-.1 2.5-.2 4.4-.2 2.2-2.6 3.4-4.5 2.4l-9.1-5.1c-1.4-.8-2-2.6-1.1-4.1.7-1.5 2.6-2.1 4-1.2zM30.9 60.9 45 46.8V30c0-1.7 1.3-3 3-3s3 1.3 3 3v18c0 .8-.3 1.6-.9 2.1l-15 15c-1.2 1.2-3.1 1.2-4.2 0-1.2-1.2-1.2-3 0-4.2z"/>',
  'HistoryOutlinedIcon',
);
