// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M66 10a12 12 0 0 1 11.5 8.6L88 54v20c0 6.6-5.4 12-12 12H20c-6.6 0-12-5.4-12-12V54l10.5-35.4C20 13.5 24.6 10 30 10h36zm0 6H30c-2.6 0-4.9 1.6-5.7 4.1l-.1.2L14.3 54h11.5c1.3 0 2.5.9 2.9 2.2l2 6.9c.5 1.6 1.9 2.8 3.6 2.9h27.2c1.7 0 3.2-1.1 3.8-2.7l.1-.2 2-6.9c.4-1.3 1.5-2.2 2.9-2.2h11.5l-10-33.7c-.7-2.5-3-4.2-5.5-4.3H66z"/>',
  'InboxFilledIcon',
);
