// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M25.1 15.5c3-5.2 9.7-7 14.9-4.1l31.3 14.7H77c6.1 0 11 4.9 11 11V75c0 6.1-4.9 11-11 11H19c-6.1 0-11-4.9-11-11V37.1c0-6 4.9-10.9 10.9-11l6.2-10.6zM77 32.1H19c-2.8 0-5 2.2-5 5V75c0 2.8 2.2 5 5 5h58c2.8 0 5-2.2 5-5V37.1c0-2.8-2.2-5-5-5zM55.3 44.8c.7-1.5 2.5-2.2 4-1.5 1.5.7 2.2 2.5 1.5 4l-10 22c-1.1 2.3-4.4 2.3-5.5 0l-10-22c-.7-1.5 0-3.3 1.5-4 1.5-.7 3.3 0 4 1.5l7.3 16 7.2-16zM37.1 16.6c-2.4-1.4-5.4-.6-6.8 1.8L25.9 26h31.4l-19.9-9.3s-.1 0-.1-.1h-.2z"/>',
  'LightVipOutlinedIcon',
);
