// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M48 8C28.7 8 13 23.7 13 43c0 13 11.2 27.7 33.2 44.4 1.1.8 2.6.8 3.6 0l1.3-1 1.3-1C72.7 69.5 83 55.5 83 43 83 23.7 67.3 8 48 8zm0 6c16 0 29 13 29 29v.3c-.2 10.1-9.6 22.7-28.4 37.5l-.6.4C28.6 66.1 19 53.3 19 43c0-16 13-29 29-29zm0 15c7.7 0 14 6.3 14 14s-6.3 14-14 14-14-6.3-14-14 6.3-14 14-14zm0 6c-4.4 0-8 3.6-8 8s3.6 8 8 8 8-3.6 8-8-3.6-8-8-8z"/>',
  'LocationOutlinedIcon',
);
