// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M35.7 52.9C37.4 47.7 42.3 44 48 44s10.6 3.7 12.3 8.9c5.8-1.1 11.4-2.9 16.7-5.5V19c0-2.8-2.2-5-5-5H24c-2.8 0-5 2.2-5 5v28.4c5.3 2.6 10.9 4.4 16.7 5.5zm25.2 6C60 65.2 54.5 70 48 70s-12-4.8-12.9-11.1c-5.6-1-11-2.6-16.1-4.9v23c0 2.8 2.2 5 5 5h48c2.8 0 5-2.2 5-5V54c-5.2 2.2-10.6 3.9-16.1 4.9zM24 8h48c6.1 0 11 4.9 11 11v58c0 6.1-4.9 11-11 11H24c-6.1 0-11-4.9-11-11V19c0-6.1 4.9-11 11-11zm24 56c3.9 0 7-3.1 7-7s-3.1-7-7-7-7 3.1-7 7 3.1 7 7 7z"/>',
  'LuckyMoneyOutlinedIcon',
);
