// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M74.5 16.6H64c-1.7 0-3-1.3-3-3s1.3-3 3-3h18c1.7 0 3 1.3 3 3v18c0 1.7-1.3 3-3 3s-3-1.3-3-3v-11l-9.9 9.9C74 36.3 77 43.8 77 52c0 18.2-14.8 33-33 33S11 70.2 11 52s14.8-33 33-33c7.9 0 15.1 2.8 20.8 7.4l9.7-9.8zM44 79c14.9 0 27-12.1 27-27S58.9 25 44 25 17 37.1 17 52s12.1 27 27 27z"/>',
  'MaleOutlinedIcon',
);
