// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<ellipse cx="48" cy="78" rx="25" ry="12" style="opacity:.3;fill-rule:evenodd;clip-rule:evenodd;enable-background:new"/><path d="M48 78c-4.4 0-32-21.4-32-39S30.3 7 48 7s32 14.3 32 32-27.6 39-32 39zm0-29.3c5.4 0 9.8-4.4 9.8-9.8s-4.4-9.8-9.8-9.8-9.8 4.4-9.8 9.8 4.4 9.8 9.8 9.8z"/>',
  'MapFilledIcon',
);
