// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M51 79.9V85c0 1.7-1.3 3-3 3s-3-1.3-3-3v-5.1C27.6 78.4 14 63.8 14 46v-2c0-1.7 1.3-3 3-3s3 1.3 3 3v2c0 15.5 12.5 28 28 28s28-12.5 28-28v-2c0-1.7 1.3-3 3-3s3 1.3 3 3v2c0 17.8-13.6 32.4-31 33.9zM28 28c0-11 9-20 20-20s20 9 20 20v18c0 11-9 20-20 20s-20-9-20-20V28zm6 0v18c0 7.7 6.3 14 14 14s14-6.3 14-14V28c0-7.7-6.3-14-14-14s-14 6.3-14 14z"/>',
  'MicOutlinedIcon',
);
