// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M75 13c6.1 0 11 4.9 11 11v24c0 1.7-1.3 3-3 3s-3-1.3-3-3V24c0-2.8-2.2-5-5-5H21c-2.8 0-5 2.2-5 5v48c0 2.8 2.2 5 5 5h21c1.7 0 3 1.3 3 3s-1.3 3-3 3H21c-6.1 0-11-4.9-11-11V24c0-6.1 4.9-11 11-11h54zm5 44c3.3 0 6 2.7 6 6v14c0 3.3-2.7 6-6 6H58c-3.3 0-6-2.7-6-6V63c0-3.3 2.7-6 6-6h22zm0 6H58v14h22V63zM32.2 29.8 45 42.6V40c0-1.6 1.2-2.9 2.8-3h.2c1.7 0 3 1.3 3 3v10c0 1.7-1.3 3-3 3H38c-1.7 0-3-1.3-3-3v-.2c.1-1.6 1.4-2.8 3-2.8h2.9l-13-13c-1.2-1.2-1.2-3.1 0-4.2 1.2-1.2 3.1-1.2 4.3 0z"/>',
  'MiniContractOutlinedIcon',
);
