// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M29 42h38c1.1 0 2 .9 2 2v8c0 1.1-.9 2-2 2H29c-1.1 0-2-.9-2-2v-8c0-1.1.9-2 2-2z"/>',
  'MinusIcon',
);
