// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path class="st0" d="M48 26.7c2.9 0 5.3-2.4 5.3-5.3S50.9 16 48 16s-5.3 2.4-5.3 5.3 2.4 5.4 5.3 5.4zm0 26.6c2.9 0 5.3-2.4 5.3-5.3s-2.4-5.3-5.3-5.3-5.3 2.4-5.3 5.3 2.4 5.3 5.3 5.3zM48 80c2.9 0 5.3-2.4 5.3-5.3s-2.4-5.3-5.3-5.3-5.3 2.4-5.3 5.3S45.1 80 48 80z"/>',
  'MoreVerticalOutlinedIcon',
);
