// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M9 48.6c-1.1-.3-1.9-1.2-2-2.3s.5-2.2 1.5-2.7L85.2 7.3c1-.5 2.2-.3 3 .5.8.8 1 2 .5 3L52.4 87.5c-.5 1-1.6 1.6-2.7 1.5s-2.1-.9-2.3-2l-7.7-30.7L9 48.6z"/>',
  'NearMeIcon',
);
