// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M72 8H24c-6.1 0-11 4.9-11 11v58c0 6.1 4.9 11 11 11h48c6.1 0 11-4.9 11-11V19c0-6.1-4.9-11-11-11zm0 6c2.8 0 5 2.2 5 5v58c0 2.8-2.2 5-5 5H24c-2.8 0-5-2.2-5-5V19c0-2.8 2.2-5 5-5h48zM32 41c-1.7 0-3-1.3-3-3s1.3-3 3-3h32c1.7 0 3 1.3 3 3s-1.3 3-3 3H32zm0 16c-1.7 0-3-1.3-3-3s1.3-3 3-3h20c1.7 0 3 1.3 3 3s-1.3 3-3 3H32z"/>',
  'OrderOutlinedIcon',
);
