// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M80.9 10.9c1.2-1.2 3.1-1.2 4.2 0 1.2 1.2 1.2 3.1 0 4.2L42.7 57.5c-1.2 1.2-3.1 1.2-4.2 0s-1.2-3.1 0-4.2l42.4-42.4zM80 42c0-1.7 1.3-3 3-3s3 1.3 3 3v33c0 6.1-4.9 11-11 11H21c-6.1 0-11-4.9-11-11V21c0-6.1 4.9-11 11-11h32c1.7 0 3 1.3 3 3s-1.3 3-3 3H21c-2.8 0-5 2.2-5 5v54c0 2.8 2.2 5 5 5h54c2.8 0 5-2.2 5-5V42z"/>',
  'PageEditOutlinedIcon',
);
