// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M73 11c6.1 0 11 4.9 11 11v60c0 2.4-2.7 3.8-4.7 2.5l-7.2-4.8-5.7 4.3c-1.4 1-3.4 1-4.8-.1L56 79.8 50.4 84c-1.4 1-3.4 1-4.8-.1L40 79.8 34.4 84c-1.4 1-3.4 1-4.8-.1l-5.7-4.3-7.2 4.8c-2 1.3-4.7-.1-4.7-2.5V22c0-6.1 4.9-11 11-11h50zm0 6H23c-2.8 0-5 2.2-5 5v54.4l3.7-2.5c1.5-.9 3.3-.9 4.7.1l5.6 4.2 5.6-4.2c1.4-1.1 3.4-1.1 4.8 0l5.6 4.2 5.6-4.2c1.4-1.1 3.4-1.1 4.8 0l5.6 4.2 5.6-4.2c1.4-1 3.2-1.1 4.6-.1l3.7 2.5V22c.1-2.8-2.1-5-4.9-5zM53 49c1.7 0 3 1.3 3 3s-1.3 3-3 3H33c-1.7 0-3-1.3-3-3s1.3-3 3-3h20zm10-16c1.7 0 3 1.3 3 3s-1.3 3-3 3H33c-1.7 0-3-1.3-3-3s1.3-3 3-3h30z"/>',
  'PaperOutlinedIcon',
);
