// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M48 8c22.1 0 40 17.9 40 40S70.1 88 48 88 8 70.1 8 48 25.9 8 48 8zm0 6c-18.8 0-34 15.2-34 34s15.2 34 34 34 34-15.2 34-34-15.2-34-34-34zm-7.7 17c.6 0 1.2.2 1.7.5l23.4 13.8c1.6.9 2.1 2.9 1.1 4.5-.3.5-.7.8-1.1 1.1L42 64.5c-1.6.9-3.6.4-4.5-1.1-.3-.5-.5-1.1-.5-1.7V34.2c0-1.7 1.5-3.2 3.3-3.2z"/>',
  'PlayCircleOutlinedIcon',
);
