// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M48 9c21.5 0 39 17.5 39 39S69.5 87 48 87 9 69.5 9 48 26.5 9 48 9zm0 9c-16.6 0-30 13.4-30 30s13.4 30 30 30 30-13.4 30-30-13.4-30-30-30zm-8.7 14c.6 0 1.2.2 1.7.4l23.4 13.3c1.6.9 2.1 2.8 1.1 4.3-.3.4-.7.8-1.1 1.1L41 64.6c-1.6.9-3.6.4-4.5-1.1-.3-.5-.5-1.1-.5-1.7V35.2c0-1.8 1.5-3.2 3.3-3.2z"/>',
  'PlayCircleOutlinedBoldIcon',
);
