// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M34.4 11c11.2 0 20.3 9.1 20.4 20.3.8-.1 1.7-.1 2.5-.1C72 31.2 84 43.3 84 58.1S72 85 57.2 85h-7.3c-1.7 0-3-1.3-3-3s1.3-3 3-3h7.3C68.7 79 78 69.6 78 58.1s-9.3-20.9-20.8-20.9c-1.7 0-3.4.2-5.1.6-2.1.5-4.1-1.3-3.7-3.5.2-.9.3-1.9.3-2.9 0-8-6.4-14.5-14.4-14.5S20 23.5 20 31.5V49c0 1.7-1.3 3-3 3s-3-1.3-3-3V31.5C14 20.2 23.1 11 34.4 11zM17 60c1.7 0 3 1.3 3 3l.2 16H36c1.7 0 3 1.3 3 3s-1.3 3-3 3H17.2c-1.6 0-3-1.3-3-3L14 63c0-1.6 1.3-3 3-3z"/>',
  'PublicWelfareOutlinedIcon',
);
