// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M66.6 76c3.4 0 6.2-1.2 8.6-3.1 2.2-2.1 3.4-5.1 3.4-8.6s-1.2-6.2-3.4-8.2C72.8 54 70 53 66.4 53c-1.4 0-2.4 0-3.2.4.8-10.3 6.4-18.6 16.8-25L74.8 20C59.6 27.8 52 40.2 52 57.1 52 69.6 56.8 76 66.6 76zm-36.2 0c3.4 0 6.4-1.2 8.8-3.1 2.2-2.1 3.4-5.1 3.4-8.6s-1.2-6.2-3.4-8.2C36.8 54 33.8 53 30.4 53c-1.4 0-2.4 0-3.2.4.6-10.3 6.2-18.7 16.8-25.1L38.6 20C23.4 27.8 16 40.2 16 57.1 16 69.6 20.8 76 30.4 76z"/>',
  'QuoteStartIcon',
);
