// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M29.4 20c-3.4 0-6.2 1.2-8.6 3.1-2.2 2.1-3.4 5.1-3.4 8.6s1.2 6.2 3.4 8.2C23.2 42 26 43 29.6 43h.6c1.1 0 1.9-.1 2.6-.4-.8 10.3-6.4 18.6-16.8 25l5.2 8.4C36.4 68.2 44 55.8 44 38.9 44 26.4 39.2 20 29.4 20zm36.2 0c-3.4 0-6.4 1.2-8.8 3.1-2.2 2.1-3.4 5.1-3.4 8.6s1.2 6.2 3.4 8.2c2.4 2.1 5.4 3.1 8.8 3.1h.6c1.1 0 1.9-.1 2.6-.4-.6 10.3-6.2 18.6-16.8 25l5.4 8.4C72.6 68.2 80 55.8 80 38.9 80 26.4 75.2 20 65.6 20z"/>',
  'QuoteEndIcon',
);
