// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M28 48a20 20 0 1 0 40 0 20 20 0 1 0-40 0"/>',
  'RadioCheckedFilledIcon',
);
