// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M58.2 13c4.3 0 7.8 3.5 7.8 7.8v.4l-.5 9.6h14.7c.3 0 .7 0 1 .1l.3.1c4.2.7 7 4.7 6.2 9l-7.1 36.9c-.6 3.5-3.8 6.1-7.4 6.1H22.8c-3.8 0-7.1-2.8-7.7-6.6L8.7 33.3c-.6-4.2 2.3-8.2 6.5-8.8.4-.1.8-.1 1.2-.1h13.9l-.3-3.2c-.2-4.2 3-7.8 7.2-8.2h21zm-28 17.4H16.1c-1 .1-1.6 1-1.5 2l6.5 43.1c.1.9.9 1.5 1.7 1.5h10l-.7-14.2-1.9-32.4zm28-11.4H37.7c-1 0-1.7.8-1.7 1.7v.1l2.1 41.4L39 77h18.2L60 20.9v-.1c0-1-.8-1.8-1.8-1.8zm22 17.8H65.8L63.2 77h9.9c.8 0 1.5-.6 1.6-1.5l7-36.7c.2-1-.5-1.9-1.4-2h-.1z"/>',
  'RankingOutlinedIcon',
);
