// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M77.1 44.4c-1.4-.8-3.3-.3-4.1 1.1-.8 1.4-.3 3.3 1.1 4.1l9.1 5.1c1.9 1.1 4.3-.2 4.5-2.4.2-1.8.3-3.3.3-4.3C88 25.9 70.1 8 48 8S8 25.9 8 48s17.9 40 40 40c13.5 0 25.9-6.8 33.3-17.8.9-1.4.6-3.2-.8-4.2-1.4-.9-3.2-.6-4.2.8C70 76.3 59.5 82 48 82c-18.8 0-34-15.2-34-34s15.2-34 34-34c18.5 0 33.5 14.7 34 33.1l-4.9-2.7z"/>',
  'RefreshOutlinedIcon',
);
