// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M65 16c-1.7 0-3-1.3-3-3s1.3-3 3-3h14c3.9 0 7 3.1 7 7v14c0 1.7-1.3 3-3 3s-3-1.3-3-3V17c0-.6-.4-1-1-1H65zm15 49c0-1.7 1.3-3 3-3s3 1.3 3 3v14c0 3.9-3.1 7-7 7H65c-1.7 0-3-1.3-3-3s1.3-3 3-3h14c.6 0 1-.4 1-1V65zM31 80c1.7 0 3 1.3 3 3s-1.3 3-3 3H17c-3.9 0-7-3.1-7-7V65c0-1.7 1.3-3 3-3s3 1.3 3 3v14c0 .6.4 1 1 1h14zM16 31c0 1.7-1.3 3-3 3s-3-1.3-3-3V17c0-3.9 3.1-7 7-7h14c1.7 0 3 1.3 3 3s-1.3 3-3 3H17c-.6 0-1 .4-1 1v14zm59 14c1.7 0 3 1.3 3 3s-1.3 3-3 3H21c-1.7 0-3-1.3-3-3s1.3-3 3-3h54z"/>',
  'ScanOutlinedIcon',
);
