// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M47.5 6.6c21.9 0 39.7 17.8 39.7 39.7s-3.3 18-8.7 24.8l12.2 12.1c1.7 1.7 1.7 4.4 0 6.1-1.7 1.7-4.4 1.7-6.1 0L72.4 77.2c-6.8 5.5-15.4 8.7-24.8 8.7-21.9 0-39.7-17.8-39.7-39.7S25.6 6.6 47.5 6.6Zm0 8.6c-17.2 0-31.1 13.9-31.1 31.1s13.9 31.1 31.1 31.1 31.1-13.9 31.1-31.1-13.9-31.1-31.1-31.1Z"/>',
  'SearchOutlinedBoldIcon',
);
