// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M47 12c1.7 0 3 1.3 3 3s-1.3 3-3 3H24c-5 0-9 4-9 9v42c0 5 4 9 9 9h48c5 0 9-4 9-9V49c0-1.7 1.3-3 3-3s3 1.3 3 3v20c0 8.3-6.7 15-15 15H24c-8.3 0-15-6.7-15-15V27c0-8.3 6.7-15 15-15h23zm27.1.9 12 12c1.9 1.9.6 5.1-2.1 5.1h-7.9C61.8 30 50 41 49 55.2c-.1 1.7-1.6 2.9-3.2 2.8-1.7-.1-2.9-1.6-2.8-3.2C44.2 37.4 58.7 24 76.1 24h.7l-6.9-6.9c-1.1-1.1-1.2-2.9-.1-4.1l.1-.1c1.1-1.2 3-1.2 4.2 0z"/>',
  'ShareIcon',
);
