// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M57 36c3.6 2.7 6 7.1 6 12 0 8.3-6.7 15-15 15s-15-6.7-15-15 6.7-15 15-15c3.4 0 6.5 1.1 9 3V17c0-1.7 1.3-3 3-3s3 1.3 3 3v31c0 1.7-1.3 3-3 3s-3-1.3-3-3V36zM48 8c1.7 0 3 1.3 3 3s-1.3 3-3 3c-18.8 0-34 15.2-34 34s15.2 34 34 34 34-15.2 34-34c0-5.5-1.3-10.8-3.8-15.6-.8-1.5-.2-3.3 1.3-4 1.5-.8 3.3-.2 4 1.3 3 5.6 4.5 11.8 4.5 18.3 0 22.1-17.9 40-40 40S8 70.1 8 48 25.9 8 48 8zm0 49c5 0 9-4 9-9s-4-9-9-9-9 4-9 9 4 9 9 9zm20-31c-5.8 0-11-4-11-9s5.2-9 11-9c5.9 0 11 3.8 11 9s-5.1 9-11 9zm0-6c2.9 0 5-1.6 5-3s-2.1-3-5-3c-2.8 0-5 1.7-5 3s2.2 3 5 3z"/>',
  'ShowOutlinedIcon',
);
