// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M48 8c3.1 0 6.1.4 9 1v27c-2.5-1.9-5.6-3-9-3-8.3 0-15 6.7-15 15s6.7 15 15 15 15-6.7 15-15V11c14.7 5.8 25 20.2 25 37 0 22.1-17.9 40-40 40S8 70.1 8 48 25.9 8 48 8z"/>',
  'ShowFilledIcon',
);
