// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M48 88C25.9 88 8 70.1 8 48S25.9 8 48 8s40 17.9 40 40-17.9 40-40 40zm0-6c18.8 0 34-15.2 34-34S66.8 14 48 14 14 29.2 14 48s15.2 34 34 34zM34.6 64.2c-1.3-1.1-1.4-3-.4-4.2 1.1-1.3 3-1.4 4.2-.4 2.7 2.2 6 3.5 9.6 3.5 3.6 0 6.9-1.2 9.6-3.5 1.3-1.1 3.2-.9 4.2.4 1.1 1.3.9 3.2-.4 4.2C57.7 67.3 53 69 48 69s-9.7-1.7-13.4-4.8z"/>',
  'SmileOutlinedIcon',
);
