// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M31.4 85.9c-3.4 2.1-7.8 1-9.8-2.4-1-1.6-1.3-3.5-.8-5.4l4.4-18.6c.1-.4 0-.9-.4-1.2L10.5 45.9c-3-2.6-3.3-7.1-.8-10.1 1.2-1.5 3-2.4 4.8-2.5l18.7-1.5c.4 0 .8-.3.9-.7l7.2-17.6c1.5-3.7 5.7-5.4 9.3-3.9 1.7.7 3.1 2.1 3.8 3.9l7.2 17.6c.2.4.5.7.9.7l18.7 1.5c3.9.3 6.8 3.8 6.5 7.7-.1 1.9-1 3.6-2.4 4.9l-14 12.5c-.3.3-.5.8-.4 1.2l4.4 18.6c.9 3.8-1.4 7.7-5.3 8.6-1.8.4-3.8.1-5.4-.9l-16-10c-.3-.2-.8-.2-1.1 0l-16.1 10z"/>',
  'StarFilledIcon',
);
