// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M47.4 70 26.3 84.6c-.9.6-2.2.4-2.8-.5-.3-.5-.4-1.1-.3-1.7l7.5-24.5c.1-.4 0-.8-.4-1.1L9.8 41.3c-.9-.7-1.1-1.9-.4-2.8.4-.5.9-.8 1.6-.8l25.8-.5c.4 0 .8-.3.9-.7l8.5-24.2c.4-1 1.5-1.6 2.5-1.2.6.2 1 .7 1.2 1.2l8.5 24.2c.1.4.5.7.9.7l25.7.5c1.1 0 2 .9 2 2 0 .6-.3 1.2-.8 1.5L65.7 56.8c-.3.3-.5.7-.4 1.1l7.5 24.5c.3 1.1-.3 2.2-1.3 2.5-.6.2-1.2.1-1.7-.3L48.6 70c-.4-.2-.8-.2-1.2 0z"/>',
  'StarFilledSharpIcon',
);
