// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="m28 44.7 12.3 12.1L68 29.4c1.8-1.8 4.8-1.8 6.6 0 1.8 1.8 1.8 4.7 0 6.5l-31 30.7c-1.8 1.8-4.8 1.8-6.6 0L21.4 51.3c-1.8-1.8-1.8-4.7 0-6.5 1.8-1.8 4.7-1.9 6.6-.1z"/>',
  'SuccessFilledBoldIcon',
);
