// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M48 8c22.1 0 40 17.9 40 40S70.1 88 48 88 8 70.1 8 48 25.9 8 48 8zm0 6c-18.8 0-34 15.2-34 34s15.2 34 34 34 34-15.2 34-34-15.2-34-34-34zm17.1 21.9c1.2 1.2 1.2 3.1 0 4.2l-20 20c-1.2 1.2-3.1 1.2-4.2 0l-10-10c-1.2-1.2-1.2-3.1 0-4.2s3.1-1.2 4.2 0l7.9 7.9 17.9-17.9c1.1-1.2 3-1.2 4.2 0z"/>',
  'SuccessCircleOutlinedIcon',
);
