// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M21.1 43.9 39 61.8l34.9-34.9c1.2-1.2 3.1-1.2 4.2 0 1.2 1.2 1.2 3.1 0 4.2l-37 37c-1.2 1.2-3.1 1.2-4.2 0l-20-20c-1.2-1.2-1.2-3.1 0-4.2s3-1.2 4.2 0z"/>',
  'SuccessFilledIcon',
);
