// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M77 13c6.1 0 11 4.9 11 11v14c0 1.7-1.3 3-3 3-3.9 0-7 3.1-7 7s3.1 7 7 7c1.7 0 3 1.3 3 3v14c0 6.1-4.9 11-11 11H19c-6.1 0-11-4.9-11-11V58c0-1.7 1.3-3 3-3 3.9 0 7-3.1 7-7s-3.1-7-7-7c-1.7 0-3-1.3-3-3V24c0-6.1 4.9-11 11-11h58zM60 53H36c-1.7 0-3 1.3-3 3s1.3 3 3 3h24c1.7 0 3-1.3 3-3s-1.3-3-3-3zm0-16H36c-1.7 0-3 1.3-3 3s1.3 3 3 3h24c1.7 0 3-1.3 3-3s-1.3-3-3-3z"/>',
  'TicketFilledIcon',
);
