// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M48 88C25.9 88 8 70.1 8 48S25.9 8 48 8s40 17.9 40 40-17.9 40-40 40zm0-6c18.8 0 34-15.2 34-34S66.8 14 48 14 14 29.2 14 48s15.2 34 34 34zm.8-24.9-7.6-8.3-9 9.3c-1.2 1.2-3 1.2-4.2.1-1.2-1.2-1.2-3-.1-4.2L39 42.3c1.2-1.2 3.2-1.2 4.4.1l7.7 8.4L63.9 38c1.2-1.2 3.1-1.2 4.2 0 1.2 1.2 1.2 3.1 0 4.2l-15 15.1c-1.2 1.1-3.2 1.1-4.3-.2z"/>',
  'TrendingCircleOutlinedIcon',
);
