// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M17 15c.6 0 1 .4 1 1v16c0 .6-.4 1-1 1s-1-.4-1-1V16c0-.6.4-1 1-1zm14 0c.6 0 1 .4 1 1v16c0 .6-.4 1-1 1s-1-.4-1-1V16c0-.6.4-1 1-1zm-7 0c.6 0 1 .4 1 1v16c0 .6-.4 1-1 1s-1-.4-1-1V16c0-.6.4-1 1-1z"/>',
  'TripleVerticalLineIcon',
);
