// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M46 8c-8.8 0-16 7.2-16 16s7.2 16 16 16 16-7.2 16-16S54.8 8 46 8zm0 6c5.5 0 10 4.5 10 10s-4.5 10-10 10-10-4.5-10-10 4.5-10 10-10zm0 29c7.1 0 13.9 2.3 19.5 6.4 1.3 1 1.6 2.9.6 4.2-1 1.3-2.9 1.6-4.2.6C57.4 50.8 51.8 49 46 49c-14.9 0-27 12.1-27 27v6l27 .2c1.6 0 2.9 1.3 3 2.8v.2c0 1.7-1.4 3-3 3L16 88c-1.6 0-3-1.4-3-3v-9c0-18.2 14.8-33 33-33zm33.5 11c.8-1.4 2.6-1.8 4-1s2 2.6 1.2 4L68.6 85c-.8 1.4-2.6 1.8-4 1l-12.1-7c-1.4-.8-2-2.6-1.2-4l.1-.1c.8-1.3 2.6-1.6 3.9-.8l9.5 5.5L79.5 54z"/>',
  'UserFollowedOutlinedIcon',
);
