// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M51 15c18.2 0 33 14.8 33 33S69.2 81 51 81H16c-2.2 0-4-1.8-4-4V48c0-18.2 14.8-33 33-33h6zm11.2 16.3c-1.5-.7-3.3 0-4 1.5l-9.9 22.1-10.6-22.2c-.7-1.5-2.5-2.1-4-1.4-1.5.7-2.1 2.5-1.4 4l13.5 28c1.1 2.3 4.4 2.3 5.4-.1l12.5-28c.7-1.5 0-3.3-1.5-3.9z"/>',
  'VerifiedFilledIcon',
);
