// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="m29.2 34.8 15-19c.2-.3.5-.6.8-.8 2.1-1.7 5.2-1.3 6.9.8l15 19 14.4-6.2c.9-.4 1.9-.5 2.9-.3 2.6.5 4.3 3.1 3.8 5.8l-8.4 40.4c-1 4.9-5.3 8.4-10.3 8.4H26.8c-5 0-9.3-3.5-10.3-8.4L8.1 34.1c-.2-1-.1-2 .3-2.9 1.1-2.5 3.9-3.6 6.4-2.6l14.4 6.2zM48 20.7 33.3 39.2c-1.4 1.7-3.7 2.3-5.8 1.5L14.4 35l8 38.3c.4 2.1 2.3 3.6 4.4 3.6h42.4c2.2 0 4-1.5 4.4-3.6l8-38.3-13.2 5.6c-2 .9-4.4.3-5.8-1.5L48 20.7z"/>',
  'VipOutlinedIcon',
);
