// Automatically generated by cli tools, please do not modify this file directly
import createSvgIcon from '../utils/createSvgIcon';

export default createSvgIcon(
  '<path d="M75 10c6 0 10.8 4.8 11 10.7V75c0 6-4.8 10.8-10.7 11H21c-6 0-10.8-4.8-11-10.7V21c0-6 4.8-10.8 10.7-11H75zm0 6H21c-2.7 0-4.9 2.1-5 4.8V75c0 2.7 2.1 4.9 4.8 5H75c2.7 0 4.9-2.1 5-4.8V21c0-2.7-2.1-4.9-4.8-5H75zm-8.6 33.4c1.7 0 3 1.3 3 3s-1.3 3-3 3h-3l10.7 10.7c1.2 1.2 1.2 3.1 0 4.2-1.2 1.2-3.1 1.2-4.2 0L59.4 59.9v2.5c0 1.6-1.2 2.9-2.8 3h-.2c-1.7 0-3-1.3-3-3v-10c0-1.7 1.3-3 3-3h10zM28.6 25.3 39 35.8v-2.5c0-1.6 1.2-2.9 2.8-3h.2c1.7 0 3 1.3 3 3v10c0 1.7-1.3 3-3 3H32c-1.7 0-3-1.3-3-3s1.3-3 3-3h3L24.3 29.6c-1.2-1.2-1.2-3.1 0-4.2s3.1-1.2 4.3-.1z"/>',
  'ZoomInOutlinedIcon',
);
