# 构建和发布官网
name: Build and Deploy Docs Website

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '9'

      - name: Install Dependencies
        run: pnpm install

      - name: Check Tag for Beta
        id: check_tag
        run: |
          TAG=$(echo ${GITHUB_REF} | sed 's|refs/tags/||')
          MAJOR=$(echo ${TAG} | sed -E 's|^v([0-9]+)\..*|\1|')
          MAJOR_TAG="v${MAJOR}"
          echo "TAG=${TAG}" >> $GITHUB_ENV
          echo "MAJOR_TAG=${MAJOR_TAG}" >> $GITHUB_ENV
          echo "Current TAG: ${TAG}"
          echo "Major TAG: ${MAJOR_TAG}"

      - name: Build Docs for Beta
        if: contains(env.TAG, 'beta') == true
        run: pnpm docs:build:beta beta

      - name: Deploy Beta to GitHub Pages
        if: contains(env.TAG, 'beta') == true
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs-dist/beta
          target-folder: beta
          force: false
          clean: true

      - name: Build Docs for Current
        if: contains(env.TAG, 'beta') == false
        run: pnpm docs:build v1

      - name: Deploy Latest to GitHub Pages
        if: contains(env.TAG, 'beta') == false
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs-dist/v1
          force: false
          clean: true
          # 若存在老版本，需要在此添加老版本目录
          clean-exclude: |
            beta/**
